import collections
import enum
import typing
from typing import Any

import gi
from gi.repository import GLib, GObject

import Babl

_namespace: str = "Gegl"
_version: str = "0.4"

class Color(GObject.Object):
    @classmethod
    def new(cls, string: str) -> Color: ...
    def duplicate(self) -> Color: ...
    def get_bytes(self, format: Babl.Object) -> GLib.Bytes: ...
    def get_cmyk(
        self, space: Babl.Object | None = None
    ) -> tuple[float, float, float, float, float]: ...
    def get_components(self, format: GObject.Value) -> list[float]: ...
    def get_format(self) -> Babl.Object: ...
    def get_hsla(
        self, space: Babl.Object | None = None
    ) -> tuple[float, float, float, float]: ...
    def get_hsva(
        self, space: Babl.Object | None = None
    ) -> tuple[float, float, float, float]: ...
    def get_rgba(self) -> tuple[float, float, float, float]: ...
    def get_rgba_with_space(
        self, space: Babl.Object
    ) -> tuple[float, float, float, float]: ...
    def set_bytes(self, format: Babl.Object, bytes: GLib.Bytes) -> None: ...
    def set_cmyk(
        self,
        cyan: float,
        magenta: float,
        yellow: float,
        key: float,
        alpha: float,
        space: Babl.Object | None = None,
    ) -> None: ...
    def set_components(
        self, format: GObject.Value, components: list[float]
    ) -> None: ...
    def set_hsla(
        self,
        hue: float,
        saturation: float,
        lightness: float,
        alpha: float,
        space: Babl.Object | None = None,
    ) -> None: ...
    def set_hsva(
        self,
        hue: float,
        saturation: float,
        value: float,
        alpha: float,
        space: Babl.Object | None = None,
    ) -> None: ...
    def set_rgba(self, red: float, green: float, blue: float, alpha: float) -> None: ...
    def set_rgba_with_space(
        self, red: float, green: float, blue: float, alpha: float, space: Babl.Object
    ) -> None: ...
    @property
    def parent_instance(self) -> Any: ...
    @property
    def priv(self) -> Any: ...

class TileSource(GObject.Object):
    @property
    def parent_instance(self) -> Any: ...
    @property
    def command(self) -> Any: ...
    @property
    def padding(self) -> Any: ...

class TileHandler(TileSource):
    def damage_rect(self, rect: Rectangle) -> None: ...
    def damage_tile(self, x: int, y: int, z: int, damage: int) -> None: ...
    def lock(self) -> None: ...
    def set_source(self, source: TileSource) -> None: ...
    def unlock(self) -> None: ...
    @property
    def parent_instance(self) -> Any: ...
    @property
    def source(self) -> Any: ...
    @property
    def priv(self) -> Any: ...

class Buffer(TileHandler):
    @classmethod
    def new(
        cls, format_name: str, x: int, y: int, width: int, height: int
    ) -> Buffer: ...
    @classmethod
    def new_for_backend(cls, extent: Rectangle, backend: TileBackend) -> Buffer: ...
    @staticmethod
    def load(path: str) -> Buffer: ...
    @staticmethod
    def open(path: str) -> Buffer: ...
    @staticmethod
    def swap_create_file(suffix: str | None = None) -> str | None: ...
    @staticmethod
    def swap_has_file(path: str) -> bool: ...
    @staticmethod
    def swap_remove_file(path: str) -> None: ...
    def add_handler(self, handler: Any = None) -> None: ...
    def clear(self, roi: Rectangle) -> None: ...
    def copy(
        self,
        src_rect: Rectangle,
        repeat_mode: AbyssPolicy,
        dst: Buffer,
        dst_rect: Rectangle,
    ) -> None: ...
    def create_sub_buffer(self, extent: Rectangle) -> Buffer: ...
    def dup(self) -> Buffer: ...
    def flush(self) -> None: ...
    def flush_ext(self, rect: Rectangle) -> None: ...
    def freeze_changed(self) -> None: ...
    def get_abyss(self) -> Rectangle: ...
    def get_extent(self) -> Rectangle: ...
    def get(
        self,
        rect: Rectangle,
        scale: float,
        format_name: str | None,
        repeat_mode: AbyssPolicy,
    ) -> list[int]: ...
    def set(self, rect: Rectangle, format_name: str, src: list[int]) -> None: ...
    def linear_close(self, linear: Any = None) -> None: ...
    def remove_handler(self, handler: Any = None) -> None: ...
    def sample_cleanup(self) -> None: ...
    def save(self, path: str, roi: Rectangle) -> None: ...
    def set_abyss(self, abyss: Rectangle) -> bool: ...
    def set_color(self, rect: Rectangle, color: Color) -> None: ...
    def set_color_from_pixel(
        self, rect: Rectangle, pixel: Any, pixel_format: Babl.Object
    ) -> None: ...
    def set_extent(self, extent: Rectangle) -> bool: ...
    def set_pattern(
        self, rect: Rectangle, pattern: Buffer, x_offset: int, y_offset: int
    ) -> None: ...
    def share_storage(self, buffer2: Buffer) -> bool: ...
    def signal_connect(
        self,
        detailed_signal: str,
        c_handler: collections.abc.Callable[[], None],
        data: Any = None,
    ) -> int: ...
    def thaw_changed(self) -> None: ...

class Rectangle(gi.Boxed):
    @property
    def x(self) -> Any: ...
    @property
    def y(self) -> Any: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @classmethod
    def new(cls, x: int, y: int, width: int, height: int) -> Rectangle: ...
    def align(
        self, rectangle: Rectangle, tile: Rectangle, alignment: RectangleAlignment
    ) -> bool: ...
    def align_to_buffer(
        self, rectangle: Rectangle, buffer: Buffer, alignment: RectangleAlignment
    ) -> bool: ...
    def bounding_box(self, source1: Rectangle, source2: Rectangle) -> None: ...
    def contains(self, child: Rectangle) -> bool: ...
    def copy(self, source: Rectangle) -> None: ...
    def dump(self) -> None: ...
    def dup(self) -> Rectangle: ...
    def equal(self, rectangle2: Rectangle) -> bool: ...
    def equal_coords(self, x: int, y: int, width: int, height: int) -> bool: ...
    def intersect(self, src1: Rectangle, src2: Rectangle) -> bool: ...
    def is_empty(self) -> bool: ...
    def is_infinite_plane(self) -> bool: ...
    def set(self, x: int, y: int, width: int, height: int) -> None: ...
    def subtract(self, minuend: Rectangle, subtrahend: Rectangle) -> int: ...
    def subtract_bounding_box(
        self, minuend: Rectangle, subtrahend: Rectangle
    ) -> bool: ...
    def xor(self, source1: Rectangle, source2: Rectangle) -> int: ...
    @staticmethod
    def infinite_plane() -> Rectangle: ...

class DistanceMetric(GObject.GEnum):
    EUCLIDEAN = 0
    MANHATTAN = 1
    CHEBYSHEV = 2

AUTO_ROWSTRIDE: int = 0

class AbyssPolicy(GObject.GEnum):
    NONE = 0
    CLAMP = 1
    LOOP = 2
    BLACK = 3
    WHITE = 4

class AccessMode(GObject.GFlags):
    READ = 1
    WRITE = 2

class AudioFragment(GObject.Object):
    @classmethod
    def new(
        cls, sample_rate: int, channels: int, channel_layout: int, max_samples: int
    ) -> AudioFragment: ...
    def get_channel_layout(self) -> int: ...
    def get_channels(self) -> int: ...
    def get_max_samples(self) -> int: ...
    def get_pos(self) -> int: ...
    def get_sample_count(self) -> int: ...
    def get_sample_rate(self) -> int: ...
    def set_channel_layout(self, channel_layout: int) -> None: ...
    def set_channels(self, channels: int) -> None: ...
    def set_max_samples(self, max_samples: int) -> None: ...
    def set_pos(self, pos: int) -> None: ...
    def set_sample_count(self, sample_count: int) -> None: ...
    def set_sample_rate(self, sample_rate: int) -> None: ...
    @property
    def parent_instance(self) -> Any: ...
    @property
    def data(self) -> Any: ...
    @property
    def priv(self) -> Any: ...

class AudioFragmentClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class AudioFragmentPrivate(gi.Struct):
    pass

class BablVariant(GObject.GEnum):
    FLOAT = 0
    LINEAR = 1
    NON_LINEAR = 2
    PERCEPTUAL = 3
    LINEAR_PREMULTIPLIED = 4
    PERCEPTUAL_PREMULTIPLIED = 5
    LINEAR_PREMULTIPLIED_IF_ALPHA = 6
    PERCEPTUAL_PREMULTIPLIED_IF_ALPHA = 7
    ADD_ALPHA = 8

class BlitFlags(enum.IntFlag):
    CACHE = 1
    DIRTY = 2

class BufferIterator(gi.Struct):
    @property
    def length(self) -> Any: ...
    @property
    def priv(self) -> Any: ...
    @property
    def items(self) -> Any: ...

class BufferIteratorItem(gi.Struct):
    @property
    def data(self) -> Any: ...
    @property
    def roi(self) -> Any: ...

class BufferIteratorPriv(gi.Struct):
    pass

class BufferMatrix2(gi.Struct):
    @property
    def coeff(self) -> Any: ...
    def determinant(self) -> float: ...
    def is_identity(self) -> bool: ...
    def is_scale(self) -> bool: ...

CH_BACK_CENTER: int = 256
CH_BACK_LEFT: int = 16
CH_BACK_RIGHT: int = 32
CH_FRONT_CENTER: int = 4
CH_FRONT_LEFT: int = 1
CH_FRONT_LEFT_OF_CENTER: int = 64
CH_FRONT_RIGHT: int = 2
CH_FRONT_RIGHT_OF_CENTER: int = 128
CH_LAYOUT_2POINT1: int = 0
CH_LAYOUT_2_1: int = 0
CH_LAYOUT_2_2: int = 0
CH_LAYOUT_3POINT1: int = 0
CH_LAYOUT_4POINT0: int = 0
CH_LAYOUT_4POINT1: int = 0
CH_LAYOUT_5POINT0: int = 0
CH_LAYOUT_5POINT0_BACK: int = 0
CH_LAYOUT_5POINT1: int = 0
CH_LAYOUT_5POINT1_BACK: int = 0
CH_LAYOUT_6POINT0: int = 0
CH_LAYOUT_6POINT0_FRONT: int = 0
CH_LAYOUT_6POINT1: int = 0
CH_LAYOUT_6POINT1_BACK: int = 0
CH_LAYOUT_6POINT1_FRONT: int = 0
CH_LAYOUT_7POINT0: int = 0
CH_LAYOUT_7POINT0_FRONT: int = 0
CH_LAYOUT_7POINT1: int = 0
CH_LAYOUT_7POINT1_WIDE: int = 0
CH_LAYOUT_7POINT1_WIDE_BACK: int = 0
CH_LAYOUT_HEXADECAGONAL: int = 0
CH_LAYOUT_HEXAGONAL: int = 0
CH_LAYOUT_NATIVE: int = -1
CH_LAYOUT_OCTAGONAL: int = 0
CH_LAYOUT_QUAD: int = 0
CH_LAYOUT_STEREO: int = 0
CH_LAYOUT_STEREO_DOWNMIX: int = 0
CH_LAYOUT_SURROUND: int = 0
CH_LOW_FREQUENCY: int = 8
CH_LOW_FREQUENCY_2: int = 0
CH_SIDE_LEFT: int = 512
CH_SIDE_RIGHT: int = 1024
CH_STEREO_LEFT: int = 536870912
CH_STEREO_RIGHT: int = 1073741824
CH_SURROUND_DIRECT_LEFT: int = 0
CH_SURROUND_DIRECT_RIGHT: int = 0
CH_TOP_BACK_CENTER: int = 65536
CH_TOP_BACK_LEFT: int = 32768
CH_TOP_BACK_RIGHT: int = 131072
CH_TOP_CENTER: int = 2048
CH_TOP_FRONT_CENTER: int = 8192
CH_TOP_FRONT_LEFT: int = 4096
CH_TOP_FRONT_RIGHT: int = 16384
CH_WIDE_LEFT: int = -2147483648
CH_WIDE_RIGHT: int = 0

class CachePolicy(GObject.GEnum):
    AUTO = 0
    NEVER = 1
    ALWAYS = 2

class ColorClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ColorPrivate(gi.Struct):
    pass

class Config(GObject.Object):
    pass

class Curve(GObject.Object):
    @classmethod
    def new(cls, y_min: float, y_max: float) -> Curve: ...
    @classmethod
    def new_default(cls) -> Curve: ...
    def add_point(self, x: float, y: float) -> int: ...
    def calc_value(self, x: float) -> float: ...
    def duplicate(self) -> Curve: ...
    def get_point(self, index: int) -> tuple[float, float]: ...
    def get_y_bounds(self) -> tuple[float, float]: ...
    def num_points(self) -> int: ...
    def set_point(self, index: int, x: float, y: float) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class CurveClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class DitherMethod(GObject.GEnum):
    NONE = 0
    FLOYD_STEINBERG = 1
    BAYER = 2
    RANDOM = 3
    RANDOM_COVARIANT = 4
    ADD = 5
    ADD_COVARIANT = 6
    XOR = 7
    XOR_COVARIANT = 8
    BLUE_NOISE = 9
    BLUE_NOISE_COVARIANT = 10

FLOAT_EPSILON: float = 1e-05
LOOKUP_MAX_ENTRIES: int = 819200

class Lookup(gi.Struct):
    @property
    def function(self) -> Any: ...
    @property
    def data(self) -> Any: ...
    @property
    def shift(self) -> Any: ...
    @property
    def positive_min(self) -> Any: ...
    @property
    def positive_max(self) -> Any: ...
    @property
    def negative_min(self) -> Any: ...
    @property
    def negative_max(self) -> Any: ...
    @property
    def bitmask(self) -> Any: ...
    @property
    def table(self) -> Any: ...

MAJOR_VERSION: int = 0
MAX_AUDIO_CHANNELS: int = 8
MICRO_VERSION: int = 70
MINOR_VERSION: int = 4

class MapFlags(enum.IntEnum):
    MAP_EXCLUDE_UNMAPPED = 1

class Matrix3(gi.Boxed):
    @property
    def coeff(self) -> Any: ...
    @classmethod
    def new(cls) -> Matrix3: ...
    def copy(self) -> Matrix3: ...
    def copy_into(self, src: Matrix3) -> None: ...
    def determinant(self) -> float: ...
    def equal(self, matrix2: Matrix3) -> bool: ...
    def identity(self) -> None: ...
    def invert(self) -> None: ...
    def is_affine(self) -> bool: ...
    def is_identity(self) -> bool: ...
    def is_scale(self) -> bool: ...
    def is_translate(self) -> bool: ...
    def multiply(self, right: Matrix3, product: Matrix3) -> None: ...
    def originate(self, x: float, y: float) -> None: ...
    def parse_string(self, string: str) -> None: ...
    def round_error(self) -> None: ...
    def to_string(self) -> str: ...
    def transform_point(self, x: float, y: float) -> None: ...

class Metadata(GObject.GInterface):
    def get_resolution(self, unit: ResolutionUnit, x: float, y: float) -> bool: ...
    def iter_get_value(self, iter: MetadataIter, value: GObject.Value) -> bool: ...
    def iter_init(self, iter: MetadataIter) -> None: ...
    def iter_lookup(self, iter: MetadataIter, key: str) -> bool: ...
    def iter_next(self, iter: MetadataIter) -> str: ...
    def iter_set_value(self, iter: MetadataIter, value: GObject.Value) -> bool: ...
    def register_map(
        self, file_module: str, flags: int, map: list[MetadataMap]
    ) -> None: ...
    def set_resolution(self, unit: ResolutionUnit, x: float, y: float) -> bool: ...
    def unregister_map(self) -> None: ...

class MetadataStore(GObject.Object, Metadata):
    def declare(self, pspec: GObject.ParamSpec) -> None: ...
    def get_artist(self) -> str: ...
    def get_comment(self) -> str: ...
    def get_copyright(self) -> str: ...
    def get_description(self) -> str: ...
    def get_disclaimer(self) -> str: ...
    def get_file_module_name(self) -> str: ...
    def get_resolution_unit(self) -> ResolutionUnit: ...
    def get_resolution_x(self) -> float: ...
    def get_resolution_y(self) -> float: ...
    def get_software(self) -> str: ...
    def get_source(self) -> str: ...
    def get_string(self, name: str) -> str: ...
    def get_timestamp(self) -> GLib.DateTime: ...
    def get_title(self) -> str: ...
    def get_value(self, name: str, value: GObject.Value) -> GObject.Value: ...
    def get_warning(self) -> str: ...
    def has_value(self, name: str) -> bool: ...
    def notify(self, pspec: GObject.ParamSpec, shadow: bool) -> None: ...
    def register(
        self,
        local_name: str,
        name: str,
        transform: collections.abc.Callable[[GObject.Value, GObject.Value], None],
    ) -> None: ...
    def set_artist(self, artist: str) -> None: ...
    def set_comment(self, comment: str) -> None: ...
    def set_copyright(self, copyright: str) -> None: ...
    def set_description(self, description: str) -> None: ...
    def set_disclaimer(self, disclaimer: str) -> None: ...
    def set_resolution_unit(self, unit: ResolutionUnit) -> None: ...
    def set_resolution_x(self, resolution_x: float) -> None: ...
    def set_resolution_y(self, resolution_y: float) -> None: ...
    def set_software(self, software: str) -> None: ...
    def set_source(self, source: str) -> None: ...
    def set_string(self, name: str, string: str) -> None: ...
    def set_timestamp(self, timestamp: GLib.DateTime) -> None: ...
    def set_title(self, title: str) -> None: ...
    def set_value(self, name: str, value: GObject.Value) -> None: ...
    def set_warning(self, warning: str) -> None: ...
    def typeof_value(self, name: str) -> GObject.GType: ...
    def do__declare(type, self, pspec: GObject.ParamSpec, shadow: bool) -> None: ...
    def do__get_value(type, self, name: str) -> GObject.Value: ...
    def do_has_value(type, self, name: str) -> bool: ...
    def do_register_hook(type, self, file_module_name: str, flags: int) -> None: ...
    def do_set_value(type, self, name: str, value: GObject.Value) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class MetadataHash(MetadataStore):
    @classmethod
    def new(cls) -> MetadataStore: ...

class MetadataHashClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class MetadataInterface(gi.Struct):
    @property
    def base_iface(self) -> Any: ...
    @property
    def register_map(self) -> Any: ...
    @property
    def set_resolution(self) -> Any: ...
    @property
    def get_resolution(self) -> Any: ...
    @property
    def iter_lookup(self) -> Any: ...
    @property
    def iter_init(self) -> Any: ...
    @property
    def iter_next(self) -> Any: ...
    @property
    def iter_set_value(self) -> Any: ...
    @property
    def iter_get_value(self) -> Any: ...

class MetadataIter(gi.Struct):
    @property
    def stamp(self) -> Any: ...
    @property
    def user_data(self) -> Any: ...
    @property
    def user_data2(self) -> Any: ...
    @property
    def user_data3(self) -> Any: ...

class MetadataMap(gi.Struct):
    @property
    def local_name(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def transform(self) -> Any: ...

class MetadataStoreClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def _declare(self) -> Any: ...
    @property
    def pspec(self) -> Any: ...
    @property
    def set_value(self) -> Any: ...
    @property
    def _get_value(self) -> Any: ...
    @property
    def has_value(self) -> Any: ...
    @property
    def register_hook(self) -> Any: ...
    @property
    def parse_value(self) -> Any: ...
    @property
    def generate_value(self) -> Any: ...
    @property
    def padding(self) -> Any: ...

class Node(GObject.Object):
    @classmethod
    def new(cls) -> Node: ...
    @classmethod
    def new_from_file(cls, path: str) -> Node: ...
    @classmethod
    def new_from_serialized(cls, chaindata: str, path_root: str) -> Node: ...
    @classmethod
    def new_from_xml(cls, xmldata: str, path_root: str) -> Node: ...
    def add_child(self, child: Node) -> Node: ...
    def blit_buffer(
        self,
        buffer: Buffer | None,
        roi: Rectangle | None,
        level: int,
        abyss_policy: AbyssPolicy,
    ) -> None: ...
    def connect(self, a_pad_name: str, b: Node, b_pad_name: str) -> bool: ...
    def connect_from(
        self, input_pad_name: str, source: Node, output_pad_name: str
    ) -> bool: ...
    def connect_to(
        self, output_pad_name: str, sink: Node, input_pad_name: str
    ) -> bool: ...
    def create_child(self, operation: str) -> Node: ...
    def detect(self, x: int, y: int) -> Node: ...
    def disconnect(self, input_pad: str) -> bool: ...
    def find_property(self, property_name: str) -> GObject.ParamSpec: ...
    def get_children(self) -> list[Node]: ...
    def get_consumers(self, output_pad: str) -> tuple[int, list[Node], list[str]]: ...
    def get_gegl_operation(self) -> Operation | None: ...
    def get_input_proxy(self, pad_name: str) -> Node: ...
    def get_operation(self) -> str: ...
    def get_output_proxy(self, pad_name: str) -> Node: ...
    def get_pad_description(self, pad_name: str) -> str: ...
    def get_pad_label(self, pad_name: str) -> str: ...
    def get_parent(self) -> Node: ...
    def get_passthrough(self) -> bool: ...
    def get_producer(
        self, input_pad_name: str, output_pad_name: str | None = None
    ) -> Node: ...
    def has_pad(self, pad_name: str) -> bool: ...
    def get_bounding_box(self) -> Rectangle: ...
    def get_property(self, property_name: str) -> GObject.Value: ...
    def is_graph(self) -> bool: ...
    def link(self, sink: Node) -> None: ...
    def list_input_pads(self) -> list[str]: ...
    def list_output_pads(self) -> list[str]: ...
    def new_processor(self, rectangle: Rectangle) -> Processor: ...
    def process(self) -> None: ...
    def progress(self, progress: float, message: str) -> None: ...
    def remove_child(self, child: Node) -> Node: ...
    def set_enum_as_string(self, key: str, value: str) -> None: ...
    def set_passthrough(self, passthrough: bool) -> None: ...
    def set_property(self, property_name: str, value: GObject.Value) -> None: ...
    def set_time(self, time: float) -> None: ...
    def to_xml(self, path_root: str) -> str: ...
    def to_xml_full(self, tail: Node | None, path_root: str) -> str: ...

class Operation(GObject.Object):
    @staticmethod
    def find_property(operation_type: str, property_name: str) -> GObject.ParamSpec: ...
    @staticmethod
    def get_key(operation_type: str, key_name: str) -> str: ...
    @staticmethod
    def get_op_version(op_name: str) -> str: ...
    @staticmethod
    def get_property_key(
        operation_type: str, property_name: str, property_key_name: str
    ) -> str: ...
    @staticmethod
    def list_keys(operation_type: str) -> list[str]: ...
    @staticmethod
    def list_properties(operation_type: str) -> list[GObject.ParamSpec]: ...
    @staticmethod
    def list_property_keys(operation_type: str, property_name: str) -> list[str]: ...

class OperationContext(gi.Struct):
    pass

class Orientation(GObject.GEnum):
    HORIZONTAL = 0
    VERTICAL = 1

PARAM_NO_VALIDATE: int = 64

class PadType(enum.IntFlag):
    OUTPUT = 256
    INPUT = 512

class ParamAudioFragment(GObject.ParamSpec):
    pass

class ParamColor(GObject.ParamSpec):
    pass

class ParamCurve(GObject.ParamSpec):
    pass

class ParamDouble(GObject.ParamSpecDouble):
    pass

class ParamEnum(GObject.ParamSpecEnum):
    pass

class ParamFilePath(GObject.ParamSpecString):
    pass

class ParamFormat(GObject.ParamSpecPointer):
    pass

class ParamInt(GObject.ParamSpecInt):
    pass

class ParamPath(GObject.ParamSpec):
    pass

class ParamSeed(GObject.ParamSpecUInt):
    pass

class ParamSpecDouble(gi.Struct):
    @property
    def parent_instance(self) -> Any: ...
    @property
    def ui_minimum(self) -> Any: ...
    @property
    def ui_maximum(self) -> Any: ...
    @property
    def ui_gamma(self) -> Any: ...
    @property
    def ui_step_small(self) -> Any: ...
    @property
    def ui_step_big(self) -> Any: ...
    @property
    def ui_digits(self) -> Any: ...
    def set_digits(self, digits: int) -> None: ...
    def set_steps(self, small_step: float, big_step: float) -> None: ...

class ParamSpecEnum(gi.Struct):
    @property
    def parent_instance(self) -> Any: ...
    @property
    def excluded_values(self) -> Any: ...
    def exclude_value(self, value: int) -> None: ...

class ParamSpecFilePath(gi.Struct):
    @property
    def parent_instance(self) -> Any: ...
    @property
    def no_validate(self) -> Any: ...
    @property
    def null_ok(self) -> Any: ...

class ParamSpecFormat(gi.Struct):
    @property
    def parent_instance(self) -> Any: ...

class ParamSpecInt(gi.Struct):
    @property
    def parent_instance(self) -> Any: ...
    @property
    def ui_minimum(self) -> Any: ...
    @property
    def ui_maximum(self) -> Any: ...
    @property
    def ui_gamma(self) -> Any: ...
    @property
    def ui_step_small(self) -> Any: ...
    @property
    def ui_step_big(self) -> Any: ...
    def set_steps(self, small_step: int, big_step: int) -> None: ...

class ParamSpecSeed(gi.Struct):
    @property
    def parent_instance(self) -> Any: ...
    @property
    def ui_minimum(self) -> Any: ...
    @property
    def ui_maximum(self) -> Any: ...

class ParamSpecString(gi.Struct):
    @property
    def parent_instance(self) -> Any: ...
    @property
    def no_validate(self) -> Any: ...
    @property
    def null_ok(self) -> Any: ...

class ParamSpecUri(gi.Struct):
    @property
    def parent_instance(self) -> Any: ...
    @property
    def no_validate(self) -> Any: ...
    @property
    def null_ok(self) -> Any: ...

class ParamString(GObject.ParamSpecString):
    pass

class ParamUri(GObject.ParamSpecString):
    pass

class Path(GObject.Object):
    @classmethod
    def new(cls) -> Path: ...
    @classmethod
    def new_from_string(cls, instructions: str) -> Path: ...
    @staticmethod
    def add_type(type: int, items: int, description: str) -> None: ...
    def calc(self, pos: float) -> tuple[bool, float, float]: ...
    def calc_y_for_x(self, x: float) -> tuple[int, float]: ...
    def clear(self) -> None: ...
    def closest_point(self, x: float, y: float) -> tuple[float, float, float, int]: ...
    def dirty(self) -> None: ...
    def foreach(
        self,
        each_item: collections.abc.Callable[[PathItem, typing.Any], None],
        user_data: Any = None,
    ) -> None: ...
    def foreach_flat(
        self,
        each_item: collections.abc.Callable[[PathItem, typing.Any], None],
        user_data: Any = None,
    ) -> None: ...
    def freeze(self) -> None: ...
    def get_bounds(self) -> tuple[float, float, float, float]: ...
    def get_length(self) -> float: ...
    def get_matrix(self) -> Matrix3: ...
    def get_n_nodes(self) -> int: ...
    def get_node(self, index: int) -> tuple[bool, PathItem]: ...
    def insert_node(self, pos: int, node: PathItem) -> None: ...
    def is_empty(self) -> bool: ...
    def parse_string(self, instructions: str) -> None: ...
    def remove_node(self, pos: int) -> None: ...
    def replace_node(self, pos: int, node: PathItem) -> None: ...
    def set_matrix(self, matrix: Matrix3) -> None: ...
    def thaw(self) -> None: ...
    def to_string(self) -> str: ...
    @property
    def parent_instance(self) -> Any: ...

class PathClass(gi.Struct):
    pass

class PathItem(gi.Struct):
    @property
    def type(self) -> Any: ...
    @property
    def point(self) -> Any: ...

class PathList(gi.Struct):
    @property
    def next(self) -> Any: ...
    @property
    def d(self) -> Any: ...

class PathPoint(gi.Struct):
    @property
    def x(self) -> Any: ...
    @property
    def y(self) -> Any: ...

class Processor(GObject.Object):
    def get_buffer(self) -> Buffer: ...
    def set_level(self, level: int) -> None: ...
    def set_rectangle(self, rectangle: Rectangle) -> None: ...
    def set_scale(self, scale: float) -> None: ...
    def work(self) -> tuple[bool, float]: ...

class Random(gi.Boxed):
    @classmethod
    def new(cls) -> Random: ...
    @classmethod
    def new_with_seed(cls, seed: int) -> Random: ...
    def duplicate(self) -> Random: ...
    def float(self, x: int, y: int, z: int, n: int) -> float: ...
    def float_range(
        self, x: int, y: int, z: int, n: int, min: float, max: float
    ) -> float: ...
    def free(self) -> None: ...
    def int(self, x: int, y: int, z: int, n: int) -> int: ...
    def int_range(self, x: int, y: int, z: int, n: int, min: int, max: int) -> int: ...
    def set_seed(self, seed: int) -> None: ...

class RectangleAlignment(GObject.GEnum):
    SUBSET = 0
    SUPERSET = 1
    NEAREST = 2

class ResolutionUnit(GObject.GEnum):
    NONE = 0
    DPI = 1
    DPM = 2

class Sampler(gi.Struct):
    def get(
        self,
        x: float,
        y: float,
        scale: BufferMatrix2,
        output: Any,
        repeat_mode: AbyssPolicy,
    ) -> None: ...
    def get_context_rect(self) -> Rectangle: ...

class SamplerType(GObject.GEnum):
    NEAREST = 0
    LINEAR = 1
    CUBIC = 2
    NOHALO = 3
    LOHALO = 4

class SerializeFlag(enum.IntFlag):
    TRIM_DEFAULTS = 1
    VERSION = 2
    INDENT = 4
    BAKE_ANIM = 8

class SplitStrategy(enum.IntEnum):
    AUTO = 0
    HORIZONTAL = 1
    VERTICAL = 2

class Stats(GObject.Object):
    pass

class Tile(gi.Struct):
    pass

class TileBackend(TileSource):
    @staticmethod
    def unlink_swap(path: str) -> None: ...
    def command(
        self, command: TileCommand, x: int, y: int, z: int, data: Any = None
    ) -> Any | None: ...
    def get_flush_on_destroy(self) -> bool: ...
    def get_tile_height(self) -> int: ...
    def get_tile_size(self) -> int: ...
    def get_tile_width(self) -> int: ...
    def peek_storage(self) -> TileSource: ...
    def set_extent(self, rectangle: Rectangle) -> None: ...
    def set_flush_on_destroy(self, flush_on_destroy: bool) -> None: ...
    @property
    def parent_instance(self) -> Any: ...
    @property
    def priv(self) -> Any: ...

class TileBackendClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def padding(self) -> Any: ...

class TileBackendPrivate(gi.Struct):
    pass

class TileCommand(enum.IntEnum):
    EGL_TILE_IDLE = 0
    EGL_TILE_SET = 1
    EGL_TILE_GET = 2
    EGL_TILE_IS_CACHED = 3
    EGL_TILE_EXIST = 4
    EGL_TILE_VOID = 5
    EGL_TILE_FLUSH = 6
    EGL_TILE_REFETCH = 7
    EGL_TILE_REINIT = 8
    GEGL_TILE_LAST_0_4_8_COMMAND = 9
    EGL_TILE_LAST_COMMAND = 10

class TileCopyParams(gi.Struct):
    @property
    def dst_buffer(self) -> Any: ...
    @property
    def dst_x(self) -> Any: ...
    @property
    def dst_y(self) -> Any: ...
    @property
    def dst_z(self) -> Any: ...

class TileHandlerClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class TileHandlerPrivate(gi.Struct):
    pass

class TileSourceClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def padding(self) -> Any: ...

def babl_variant(format: Babl.Object, variant: BablVariant) -> Babl.Object: ...
def cl_disable() -> None: ...
def cl_init() -> bool: ...
def cl_is_accelerated() -> bool: ...
def config() -> Config: ...
def create_chain(
    ops: str, op_start: Node, op_end: Node, time: float, rel_dim: int, path_root: str
) -> None: ...
def create_chain_argv(
    ops: str, op_start: Node, op_end: Node, time: float, rel_dim: int, path_root: str
) -> None: ...
def exit() -> None: ...
def format(format_name: str) -> GObject.Value | None: ...
def format_get_name(format: GObject.Value) -> str | None: ...
def get_version() -> tuple[int, int, int]: ...
def graph_dump_outputs(node: Node) -> None: ...
def graph_dump_request(node: Node, roi: Rectangle) -> None: ...
def has_operation(operation_type: str) -> bool: ...
def init(argv: list[str] | None = None) -> list[str] | None: ...
def is_main_thread() -> bool: ...
def list_operations() -> list[str]: ...
def load_module_directory(path: str) -> None: ...
def parallel_distribute(
    max_n: int,
    func: collections.abc.Callable[[int, int, typing.Any], None],
    user_data: Any = None,
) -> None: ...
def parallel_distribute_area(
    area: Rectangle,
    thread_cost: float,
    split_strategy: SplitStrategy,
    func: collections.abc.Callable[[Rectangle, typing.Any], None],
    user_data: Any = None,
) -> None: ...
def parallel_distribute_range(
    size: int,
    thread_cost: float,
    func: collections.abc.Callable[[int, int, typing.Any], None],
    user_data: Any = None,
) -> None: ...
def param_spec_audio_fragment(
    name: str, nick: str, blurb: str, flags: GObject.ParamFlags
) -> GObject.ParamSpec: ...
def param_spec_color(
    name: str, nick: str, blurb: str, default_color: Color, flags: GObject.ParamFlags
) -> GObject.ParamSpec: ...
def param_spec_color_from_string(
    name: str,
    nick: str,
    blurb: str,
    default_color_string: str,
    flags: GObject.ParamFlags,
) -> GObject.ParamSpec: ...
def param_spec_color_get_default(self: GObject.ParamSpec) -> Color: ...
def param_spec_curve(
    name: str, nick: str, blurb: str, default_curve: Curve, flags: GObject.ParamFlags
) -> GObject.ParamSpec: ...
def param_spec_double(
    name: str,
    nick: str,
    blurb: str,
    minimum: float,
    maximum: float,
    default_value: float,
    ui_minimum: float,
    ui_maximum: float,
    ui_gamma: float,
    flags: GObject.ParamFlags,
) -> GObject.ParamSpec: ...
def param_spec_enum(
    name: str,
    nick: str,
    blurb: str,
    enum_type: GObject.GType,
    default_value: int,
    flags: GObject.ParamFlags,
) -> GObject.ParamSpec: ...
def param_spec_file_path(
    name: str,
    nick: str,
    blurb: str,
    no_validate: bool,
    null_ok: bool,
    default_value: str,
    flags: GObject.ParamFlags,
) -> GObject.ParamSpec: ...
def param_spec_format(
    name: str, nick: str, blurb: str, flags: GObject.ParamFlags
) -> GObject.ParamSpec: ...
def param_spec_get_property_key(pspec: GObject.ParamSpec, key_name: str) -> str: ...
def param_spec_int(
    name: str,
    nick: str,
    blurb: str,
    minimum: int,
    maximum: int,
    default_value: int,
    ui_minimum: int,
    ui_maximum: int,
    ui_gamma: float,
    flags: GObject.ParamFlags,
) -> GObject.ParamSpec: ...
def param_spec_path(
    name: str, nick: str, blurb: str, default_path: Path, flags: GObject.ParamFlags
) -> GObject.ParamSpec: ...
def param_spec_seed(
    name: str, nick: str, blurb: str, flags: GObject.ParamFlags
) -> GObject.ParamSpec: ...
def param_spec_set_property_key(
    pspec: GObject.ParamSpec, key_name: str, value: str
) -> None: ...
def param_spec_string(
    name: str,
    nick: str,
    blurb: str,
    no_validate: bool,
    null_ok: bool,
    default_value: str,
    flags: GObject.ParamFlags,
) -> GObject.ParamSpec: ...
def param_spec_uri(
    name: str,
    nick: str,
    blurb: str,
    no_validate: bool,
    null_ok: bool,
    default_value: str,
    flags: GObject.ParamFlags,
) -> GObject.ParamSpec: ...
def rectangle_infinite_plane() -> Rectangle: ...
def reset_stats() -> None: ...
def serialize(
    start: Node, end: Node, basepath: str, serialize_flags: SerializeFlag
) -> str: ...
def stats() -> Stats: ...
