import collections
import enum
import typing
from typing import Any

import cairo
import gi
from gi.repository import Gdk, GdkPixbuf, Gio, GLib, GObject, Gtk

import Babl
import Gegl
import Gimp

_namespace: str = "GimpUi"
_version: str = "3.0"

class Preview(Gtk.Box):
    def draw(self) -> None: ...
    def draw_buffer(self, buffer: list[int], rowstride: int) -> None: ...
    def get_area(self) -> PreviewArea: ...
    def get_bounds(self) -> tuple[int, int, int, int]: ...
    def get_controls(self) -> Gtk.Box: ...
    def get_default_cursor(self) -> Gdk.Cursor: ...
    def get_frame(self) -> Gtk.AspectFrame: ...
    def get_grid(self) -> Gtk.Grid: ...
    def get_offsets(self) -> tuple[int, int]: ...
    def get_position(self) -> tuple[int, int]: ...
    def get_size(self) -> tuple[int, int]: ...
    def get_update(self) -> bool: ...
    def invalidate(self) -> None: ...
    def set_bounds(self, xmin: int, ymin: int, xmax: int, ymax: int) -> None: ...
    def set_default_cursor(self, cursor: Gdk.Cursor) -> None: ...
    def set_offsets(self, xoff: int, yoff: int) -> None: ...
    def set_size(self, width: int, height: int) -> None: ...
    def set_update(self, update: bool) -> None: ...
    def transform(self, src_x: int, src_y: int) -> tuple[int, int]: ...
    def untransform(self, src_x: int, src_y: int) -> tuple[int, int]: ...
    def do_draw(type, self) -> None: ...
    def do_draw_buffer(type, self, buffer: list[int], rowstride: int) -> None: ...
    def do_draw_thumb(
        type, self, area: PreviewArea, width: int, height: int
    ) -> None: ...
    def do_invalidated(type, self) -> None: ...
    def do_set_cursor(type, self) -> None: ...
    def do_transform(type, self, src_x: int, src_y: int) -> tuple[int, int]: ...
    def do_untransform(type, self, src_x: int, src_y: int) -> tuple[int, int]: ...
    @property
    def parent_instance(self) -> Any: ...

class AspectPreview(Preview):
    @classmethod
    def new_from_drawable(cls, drawable: Gimp.Drawable) -> Gtk.Widget: ...

class AspectPreviewClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class AspectType(GObject.GEnum):
    SQUARE = 0
    PORTRAIT = 1
    LANDSCAPE = 2

class Browser(Gtk.Paned):
    @classmethod
    def new(cls) -> Gtk.Widget: ...
    def get_left_vbox(self) -> Gtk.Box: ...
    def get_right_vbox(self) -> Gtk.Box: ...
    def set_search_summary(self, summary: str) -> None: ...
    def set_widget(self, widget: Gtk.Widget) -> None: ...
    def show_message(self, message: str) -> None: ...

class BrowserClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ResourceChooser(Gtk.Box):
    def get_label(self) -> Gtk.Widget: ...
    def get_resource(self) -> Gimp.Resource: ...
    def set_resource(self, resource: Gimp.Resource) -> None: ...
    def do_draw_interior(type, self) -> None: ...
    def do_resource_set(
        type, self, resource: Gimp.Resource, dialog_closing: bool
    ) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class BrushChooser(ResourceChooser):
    @classmethod
    def new(
        cls,
        title: str | None = None,
        label: str | None = None,
        brush: Gimp.Brush | None = None,
    ) -> Gtk.Widget: ...

class BrushChooserClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class BusyBox(Gtk.Box):
    @classmethod
    def new(cls, message: str | None = None) -> Gtk.Widget: ...
    def get_message(self) -> str: ...
    def set_message(self, message: str) -> None: ...

class BusyBoxClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class Button(Gtk.Button):
    @classmethod
    def new(cls) -> Gtk.Widget: ...
    def extended_clicked(self, modifier_state: Gdk.ModifierType) -> None: ...
    def do_extended_clicked(type, self, modifier_state: Gdk.ModifierType) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class ButtonClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def extended_clicked(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

COLOR_SELECTOR_BAR_SIZE: int = 15
COLOR_SELECTOR_SIZE: int = 150

class CellRendererColor(Gtk.CellRenderer):
    @classmethod
    def new(cls) -> Gtk.CellRenderer: ...

class CellRendererColorClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class CellRendererToggle(Gtk.CellRendererToggle):
    @classmethod
    def new(cls, icon_name: str) -> Gtk.CellRenderer: ...
    def clicked(self, path: str, state: Gdk.ModifierType) -> None: ...

class CellRendererToggleClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ChainButton(Gtk.Grid):
    @classmethod
    def new(cls, position: ChainPosition) -> Gtk.Widget: ...
    def get_active(self) -> bool: ...
    def get_button(self) -> Gtk.Button: ...
    def get_icon_size(self) -> Gtk.IconSize: ...
    def set_active(self, active: bool) -> None: ...
    def set_icon_size(self, size: Gtk.IconSize) -> None: ...

class ChainButtonClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ChainPosition(GObject.GEnum):
    TOP = 0
    LEFT = 1
    BOTTOM = 2
    RIGHT = 3

class IntComboBox(Gtk.ComboBox):
    @classmethod
    def new(cls, labels: list[str]) -> Gtk.Widget: ...
    def connect(
        self, value: int, callback: collections.abc.Callable[[], None], data: Any = None
    ) -> int: ...
    def get_active(self) -> tuple[bool, int]: ...
    def get_active_user_data(self) -> tuple[bool, typing.Any | None]: ...
    def get_label(self) -> str: ...
    def get_layout(self) -> IntComboBoxLayout: ...
    def set_active(self, value: int) -> bool: ...
    def set_active_by_user_data(self, user_data: Any = None) -> bool: ...
    def set_label(self, label: str) -> None: ...
    def set_layout(self, layout: IntComboBoxLayout) -> None: ...
    def set_sensitivity(
        self, func: collections.abc.Callable[[int, typing.Any], bool], data: Any = None
    ) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class ChannelComboBox(IntComboBox):
    @classmethod
    def new(
        cls,
        constraint: collections.abc.Callable[[Gimp.Image, Gimp.Item, Any], bool]
        | None = None,
    ) -> Gtk.Widget: ...

class ColorArea(Gtk.DrawingArea):
    @classmethod
    def new(
        cls, color: Gegl.Color, type: ColorAreaType, drag_mask: Gdk.ModifierType
    ) -> Gtk.Widget: ...
    def enable_drag(self, drag_mask: Gdk.ModifierType) -> None: ...
    def get_color(self) -> Gegl.Color: ...
    def has_alpha(self) -> bool: ...
    def set_color(self, color: Gegl.Color) -> None: ...
    def set_color_config(self, config: Gimp.ColorConfig) -> None: ...
    def set_draw_border(self, draw_border: bool) -> None: ...
    def set_out_of_gamut(self, out_of_gamut: bool) -> None: ...
    def set_type(self, type: ColorAreaType) -> None: ...

class ColorAreaClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ColorAreaType(GObject.GEnum):
    FLAT = 0
    SMALL_CHECKS = 1
    LARGE_CHECKS = 2

class ColorButton(Button):
    @classmethod
    def new(
        cls, title: str, width: int, height: int, color: Gegl.Color, type: ColorAreaType
    ) -> Gtk.Widget: ...
    def get_action_group(self) -> Gio.SimpleActionGroup: ...
    def get_color(self) -> Gegl.Color: ...
    def get_title(self) -> str: ...
    def get_update(self) -> bool: ...
    def has_alpha(self) -> bool: ...
    def set_color(self, color: Gegl.Color) -> None: ...
    def set_color_config(self, config: Gimp.ColorConfig) -> None: ...
    def set_title(self, title: str) -> None: ...
    def set_type(self, type: ColorAreaType) -> None: ...
    def set_update(self, continuous: bool) -> None: ...
    def do_color_changed(type, self) -> None: ...
    def do_get_action_type(type, self) -> GObject.GType: ...
    @property
    def parent_instance(self) -> Any: ...

class ColorButtonClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def color_changed(self) -> Any: ...
    @property
    def get_action_type(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class ColorDisplay(GObject.Object, Gimp.ConfigInterface):
    def changed(self) -> None: ...
    def clone(self) -> ColorDisplay: ...
    def configure(self) -> Gtk.Widget: ...
    def configure_reset(self) -> None: ...
    def convert_buffer(self, buffer: Gegl.Buffer, area: Gegl.Rectangle) -> None: ...
    def get_config(self) -> Gimp.ColorConfig: ...
    def get_enabled(self) -> bool: ...
    def get_managed(self) -> Gimp.ColorManaged: ...
    def load_state(self, state: Gimp.Parasite) -> None: ...
    def save_state(self) -> Gimp.Parasite: ...
    def set_enabled(self, enabled: bool) -> None: ...
    def do_changed(type, self) -> None: ...
    def do_configure(type, self) -> Gtk.Widget: ...
    def do_convert_buffer(
        type, self, buffer: Gegl.Buffer, area: Gegl.Rectangle
    ) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class ColorDisplayClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def help_id(self) -> Any: ...
    @property
    def icon_name(self) -> Any: ...
    @property
    def convert_buffer(self) -> Any: ...
    @property
    def configure(self) -> Any: ...
    @property
    def changed(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class ColorDisplayStack(GObject.Object):
    @classmethod
    def new(cls) -> ColorDisplayStack: ...
    def add(self, display: ColorDisplay) -> None: ...
    def changed(self) -> None: ...
    def clone(self) -> ColorDisplayStack: ...
    def convert_buffer(self, buffer: Gegl.Buffer, area: Gegl.Rectangle) -> None: ...
    def get_filters(self) -> list[ColorDisplay]: ...
    def remove(self, display: ColorDisplay) -> None: ...
    def reorder_down(self, display: ColorDisplay) -> None: ...
    def reorder_up(self, display: ColorDisplay) -> None: ...

class ColorDisplayStackClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ColorHexEntry(Gtk.Entry):
    @classmethod
    def new(cls) -> Gtk.Widget: ...
    def get_color(self) -> Gegl.Color: ...
    def set_color(self, color: Gegl.Color) -> None: ...

class ColorHexEntryClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ColorSelector(Gtk.Box):
    def enable_simulation(self, enabled: bool) -> bool: ...
    def get_channel(self) -> ColorSelectorChannel: ...
    def get_color(self) -> Gegl.Color: ...
    def get_model_visible(self, model: ColorSelectorModel) -> bool: ...
    def get_show_alpha(self) -> bool: ...
    def get_simulation(
        self, profile: Gimp.ColorProfile, intent: Gimp.ColorRenderingIntent, bpc: bool
    ) -> bool: ...
    def get_toggles_sensitive(self) -> bool: ...
    def get_toggles_visible(self) -> bool: ...
    def set_channel(self, channel: ColorSelectorChannel) -> None: ...
    def set_color(self, color: Gegl.Color) -> None: ...
    def set_config(self, config: Gimp.ColorConfig) -> None: ...
    def set_format(self, format: Babl.Object) -> None: ...
    def set_model_visible(self, model: ColorSelectorModel, visible: bool) -> None: ...
    def set_show_alpha(self, show_alpha: bool) -> None: ...
    def set_simulation(
        self, profile: Gimp.ColorProfile, intent: Gimp.ColorRenderingIntent, bpc: bool
    ) -> None: ...
    def set_toggles_sensitive(self, sensitive: bool) -> None: ...
    def set_toggles_visible(self, visible: bool) -> None: ...
    def do_channel_changed(type, self, channel: ColorSelectorChannel) -> None: ...
    def do_color_changed(type, self, color: Gegl.Color) -> None: ...
    def do_model_visible_changed(
        type, self, model: ColorSelectorModel, visible: bool
    ) -> None: ...
    def do_set_channel(type, self, channel: ColorSelectorChannel) -> None: ...
    def do_set_color(type, self, color: Gegl.Color) -> None: ...
    def do_set_config(type, self, config: Gimp.ColorConfig) -> None: ...
    def do_set_format(type, self, format: Babl.Object) -> None: ...
    def do_set_model_visible(
        type, self, model: ColorSelectorModel, visible: bool
    ) -> None: ...
    def do_set_show_alpha(type, self, show_alpha: bool) -> None: ...
    def do_set_simulation(
        type,
        self,
        profile: Gimp.ColorProfile,
        intent: Gimp.ColorRenderingIntent,
        bpc: bool,
    ) -> None: ...
    def do_set_toggles_sensitive(type, self, sensitive: bool) -> None: ...
    def do_set_toggles_visible(type, self, visible: bool) -> None: ...
    def do_simulation(type, self, enabled: bool) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class ColorNotebook(ColorSelector):
    def enable_simulation(self, enabled: bool) -> None: ...
    def get_current_selector(self) -> ColorSelector: ...
    def get_notebook(self) -> Gtk.Notebook: ...
    def get_selectors(self) -> list[ColorSelector]: ...
    def set_format(self, format: Babl.Object) -> None: ...
    def set_has_page(self, page_type: GObject.GType, has_page: bool) -> Gtk.Widget: ...
    def set_simulation(
        self, profile: Gimp.ColorProfile, intent: Gimp.ColorRenderingIntent, bpc: bool
    ) -> None: ...

class ColorNotebookClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ColorProfileChooserDialog(Gtk.FileChooserDialog):
    @classmethod
    def new(
        cls, title: str, parent: Gtk.Window, action: Gtk.FileChooserAction
    ) -> Gtk.Widget: ...

class ColorProfileChooserDialogClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ColorProfileComboBox(Gtk.ComboBox):
    @classmethod
    def new(cls, dialog: Gtk.Widget, history: Gio.File) -> Gtk.Widget: ...
    @classmethod
    def new_with_model(cls, dialog: Gtk.Widget, model: Gtk.TreeModel) -> Gtk.Widget: ...
    def add_file(self, file: Gio.File, label: str) -> None: ...
    def get_active_file(self) -> Gio.File: ...
    def set_active_file(self, file: Gio.File, label: str) -> None: ...
    def set_active_profile(self, profile: Gimp.ColorProfile) -> None: ...

class ColorProfileComboBoxClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ColorProfileStore(Gtk.ListStore):
    @classmethod
    def new(cls, history: Gio.File) -> Gtk.ListStore: ...
    def add_file(self, file: Gio.File, label: str) -> None: ...

class ColorProfileStoreClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ColorProfileView(Gtk.TextView):
    @classmethod
    def new(cls) -> Gtk.Widget: ...
    def set_error(self, message: str) -> None: ...
    def set_profile(self, profile: Gimp.ColorProfile) -> None: ...

class ColorProfileViewClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ColorScale(Gtk.Scale):
    @classmethod
    def new(
        cls, orientation: Gtk.Orientation, channel: ColorSelectorChannel
    ) -> Gtk.Widget: ...
    def set_channel(self, channel: ColorSelectorChannel) -> None: ...
    def set_color(self, color: Gegl.Color) -> None: ...
    def set_color_config(self, config: Gimp.ColorConfig) -> None: ...
    def set_format(self, format: Babl.Object) -> None: ...

class ColorScaleClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class Labeled(Gtk.Grid):
    def get_label(self) -> Gtk.Label: ...
    def get_text(self) -> str: ...
    def set_text(self, text: str) -> None: ...
    def do_mnemonic_widget_changed(type, self, widget: Gtk.Widget) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class LabelSpin(Labeled):
    @classmethod
    def new(
        cls, text: str, value: float, lower: float, upper: float, digits: int
    ) -> Gtk.Widget: ...
    def get_spin_button(self) -> Gtk.Widget: ...
    def get_value(self) -> float: ...
    def set_digits(self, digits: int) -> None: ...
    def set_increments(self, step: float, page: float) -> None: ...
    def set_value(self, value: float) -> None: ...
    def do_value_changed(type, self) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class ScaleEntry(LabelSpin):
    @classmethod
    def new(
        cls, text: str, value: float, lower: float, upper: float, digits: int
    ) -> Gtk.Widget: ...
    def get_logarithmic(self) -> bool: ...
    def get_range(self) -> Gtk.Range: ...
    def set_bounds(self, lower: float, upper: float, limit_scale: bool) -> None: ...
    def set_logarithmic(self, logarithmic: bool) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class ColorScaleEntry(ScaleEntry):
    @classmethod
    def new(
        cls, text: str, value: float, lower: float, upper: float, digits: int
    ) -> Gtk.Widget: ...

class ColorScaleEntryClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ColorScales(ColorSelector):
    def get_show_rgb_u8(self) -> bool: ...
    def set_show_rgb_u8(self, show_rgb_u8: bool) -> None: ...

class ColorScalesClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ColorSelect(ColorSelector):
    pass

class ColorSelectClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ColorSelection(Gtk.Box):
    @classmethod
    def new(cls) -> Gtk.Widget: ...
    def color_changed(self) -> None: ...
    def get_color(self) -> Gegl.Color: ...
    def get_notebook(self) -> Gtk.Widget: ...
    def get_old_color(self) -> Gegl.Color: ...
    def get_right_vbox(self) -> Gtk.Box: ...
    def get_show_alpha(self) -> bool: ...
    def reset(self) -> None: ...
    def set_color(self, color: Gegl.Color) -> None: ...
    def set_config(self, config: Gimp.ColorConfig) -> None: ...
    def set_format(self, format: Babl.Object) -> None: ...
    def set_old_color(self, color: Gegl.Color) -> None: ...
    def set_show_alpha(self, show_alpha: bool) -> None: ...
    def set_simulation(
        self, profile: Gimp.ColorProfile, intent: Gimp.ColorRenderingIntent, bpc: bool
    ) -> None: ...

class ColorSelectionClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ColorSelectorChannel(GObject.GEnum):
    HUE = 0
    SATURATION = 1
    VALUE = 2
    RED = 3
    GREEN = 4
    BLUE = 5
    ALPHA = 6
    LCH_LIGHTNESS = 7
    LCH_CHROMA = 8
    LCH_HUE = 9

class ColorSelectorClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def help_id(self) -> Any: ...
    @property
    def icon_name(self) -> Any: ...
    @property
    def set_toggles_visible(self) -> Any: ...
    @property
    def set_toggles_sensitive(self) -> Any: ...
    @property
    def set_show_alpha(self) -> Any: ...
    @property
    def set_color(self) -> Any: ...
    @property
    def set_channel(self) -> Any: ...
    @property
    def set_model_visible(self) -> Any: ...
    @property
    def set_config(self) -> Any: ...
    @property
    def set_format(self) -> Any: ...
    @property
    def set_simulation(self) -> Any: ...
    @property
    def color_changed(self) -> Any: ...
    @property
    def channel_changed(self) -> Any: ...
    @property
    def model_visible_changed(self) -> Any: ...
    @property
    def simulation(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class ColorSelectorModel(GObject.GEnum):
    RGB = 0
    LCH = 1
    HSV = 2

class Controller(gi.Struct):
    pass

class Dialog(Gtk.Dialog):
    def add_button(self, button_text: str, response_id: int) -> Gtk.Widget: ...
    def get_native_handle(self) -> GLib.Bytes: ...
    def run(self) -> int: ...
    def set_alternative_button_order_from_array(self, order: list[int]) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class DialogClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class DrawableChooser(Gtk.Box):
    @classmethod
    def new(
        cls,
        title: str | None,
        label: str | None,
        drawable_type: GObject.GType,
        drawable: Gimp.Drawable | None = None,
    ) -> Gtk.Widget: ...
    def get_drawable(self) -> Gimp.Drawable: ...
    def get_label(self) -> Gtk.Widget: ...
    def set_drawable(self, drawable: Gimp.Drawable) -> None: ...

class DrawableChooserClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class DrawableComboBox(IntComboBox):
    @classmethod
    def new(
        cls,
        constraint: collections.abc.Callable[[Gimp.Image, Gimp.Item, Any], bool]
        | None = None,
    ) -> Gtk.Widget: ...

class ScrolledPreview(Preview):
    def freeze(self) -> None: ...
    def get_adjustments(self) -> tuple[Gtk.Adjustment, Gtk.Adjustment]: ...
    def set_policy(
        self, hscrollbar_policy: Gtk.PolicyType, vscrollbar_policy: Gtk.PolicyType
    ) -> None: ...
    def set_position(self, x: int, y: int) -> None: ...
    def thaw(self) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class DrawablePreview(ScrolledPreview):
    @classmethod
    def new_from_drawable(cls, drawable: Gimp.Drawable) -> Gtk.Widget: ...
    def get_drawable(self) -> Gimp.Drawable: ...

class DrawablePreviewClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class EnumComboBox(IntComboBox):
    @classmethod
    def new(cls, enum_type: GObject.GType) -> Gtk.Widget: ...
    @classmethod
    def new_with_model(cls, enum_store: EnumStore) -> Gtk.Widget: ...
    def set_icon_prefix(self, icon_prefix: str) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class EnumComboBoxClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class EnumLabel(Gtk.Label):
    @classmethod
    def new(cls, enum_type: GObject.GType, value: int) -> Gtk.Widget: ...
    def set_value(self, value: int) -> None: ...

class EnumLabelClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class IntStore(Gtk.ListStore):
    @classmethod
    def new(cls, labels: list[str]) -> Gtk.ListStore: ...
    @staticmethod
    def lookup_by_user_data(
        model: Gtk.TreeModel, user_data: Any = None
    ) -> tuple[bool, Gtk.TreeIter]: ...
    @staticmethod
    def lookup_by_value(
        model: Gtk.TreeModel, value: int
    ) -> tuple[bool, Gtk.TreeIter]: ...
    @property
    def parent_instance(self) -> Any: ...

class EnumStore(IntStore):
    @classmethod
    def new(cls, enum_type: GObject.GType) -> Gtk.ListStore: ...
    @classmethod
    def new_with_range(
        cls, enum_type: GObject.GType, minimum: int, maximum: int
    ) -> Gtk.ListStore: ...
    def set_icon_prefix(self, icon_prefix: str) -> None: ...

class EnumStoreClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ProcedureDialog(Dialog):
    @classmethod
    def new(
        cls,
        procedure: Gimp.Procedure,
        config: Gimp.ProcedureConfig,
        title: str | None = None,
    ) -> Gtk.Widget: ...
    def fill_box(
        self, container_id: str, properties: list[str] | None = None
    ) -> Gtk.Widget: ...
    def fill_expander(
        self,
        container_id: str,
        title_id: str | None,
        invert_title: bool,
        contents_id: str | None = None,
    ) -> Gtk.Widget: ...
    def fill_flowbox(
        self, container_id: str, properties: list[str] | None = None
    ) -> Gtk.Widget: ...
    def fill_frame(
        self,
        container_id: str,
        title_id: str | None,
        invert_title: bool,
        contents_id: str | None = None,
    ) -> Gtk.Widget: ...
    def fill(self, properties: list[str] | None = None) -> None: ...
    def fill_notebook(
        self, container_id: str, label_list: list[str], page_list: list[str]
    ) -> Gtk.Widget: ...
    def fill_paned(
        self,
        container_id: str,
        orientation: Gtk.Orientation,
        child1_id: str | None = None,
        child2_id: str | None = None,
    ) -> Gtk.Widget: ...
    def fill_scrolled_window(
        self, container_id: str, contents_id: str
    ) -> Gtk.Widget: ...
    def get_color_widget(
        self, property: str, editable: bool, type: ColorAreaType
    ) -> Gtk.Widget: ...
    def get_coordinates(
        self,
        coordinates_id: str,
        x_property: str,
        y_property: str,
        unit_property: str,
        unit_format: str,
        update_policy: SizeEntryUpdatePolicy,
        x_resolution: float,
        y_resolution: float,
    ) -> Gtk.Widget: ...
    def get_drawable_preview(
        self, preview_id: str, drawable: Gimp.Drawable
    ) -> Gtk.Widget: ...
    def get_int_combo(self, property: str, store: IntStore) -> Gtk.Widget: ...
    def get_int_radio(self, property: str, store: IntStore) -> Gtk.Widget: ...
    def get_label(
        self, label_id: str, text: str, is_markup: bool, with_mnemonic: bool
    ) -> Gtk.Widget: ...
    def get_scale_entry(self, property: str, factor: float) -> Gtk.Widget: ...
    def get_size_entry(
        self,
        property: str,
        property_is_pixel: bool,
        unit_property: str,
        unit_format: str,
        update_policy: SizeEntryUpdatePolicy,
        resolution: float,
    ) -> Gtk.Widget: ...
    def get_spin_scale(self, property: str, factor: float) -> Gtk.Widget: ...
    def get_widget(self, property: str, widget_type: GObject.GType) -> Gtk.Widget: ...
    def run(self) -> bool: ...
    def set_ok_label(self, ok_label: str) -> None: ...
    def set_sensitive(
        self,
        property: str,
        sensitive: bool,
        config: GObject.Object | None,
        config_property: str | None,
        config_invert: bool,
    ) -> None: ...
    def set_sensitive_if_in(
        self,
        property: str,
        config: GObject.Object | None,
        config_property: str,
        values: Gimp.ValueArray,
        in_values: bool,
    ) -> None: ...
    def do_fill_end(
        type, self, procedure: Gimp.Procedure, config: Gimp.ProcedureConfig
    ) -> None: ...
    def do_fill_start(
        type, self, procedure: Gimp.Procedure, config: Gimp.ProcedureConfig
    ) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class ExportProcedureDialog(ProcedureDialog):
    @classmethod
    def new(
        cls,
        procedure: Gimp.ExportProcedure,
        config: Gimp.ProcedureConfig,
        image: Gimp.Image,
    ) -> Gtk.Widget: ...
    def add_metadata(self, property: str) -> None: ...

class ExportProcedureDialogClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class FileChooser(Gtk.Box):
    @classmethod
    def new(
        cls,
        action: Gimp.FileChooserAction,
        label: str | None = None,
        title: str | None = None,
        file: Gio.File | None = None,
    ) -> Gtk.Widget: ...
    def get_action(self) -> Gimp.FileChooserAction: ...
    def get_file(self) -> Gio.File: ...
    def get_label(self) -> str | None: ...
    def get_label_widget(self) -> Gtk.Widget: ...
    def get_title(self) -> str | None: ...
    def set_action(self, action: Gimp.FileChooserAction) -> None: ...
    def set_file(self, file: Gio.File) -> None: ...
    def set_label(self, text: str | None = None) -> None: ...
    def set_title(self, text: str | None = None) -> None: ...

class FileChooserClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class FileEntry(gi.Struct):
    pass

class FontChooser(ResourceChooser):
    @classmethod
    def new(
        cls,
        title: str | None = None,
        label: str | None = None,
        font: Gimp.Font | None = None,
    ) -> Gtk.Widget: ...

class FontChooserClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class Frame(Gtk.Frame):
    @classmethod
    def new(cls, label: str | None = None) -> Gtk.Widget: ...
    @property
    def parent_instance(self) -> Any: ...

class FrameClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class GradientChooser(ResourceChooser):
    @classmethod
    def new(
        cls,
        title: str | None = None,
        label: str | None = None,
        gradient: Gimp.Gradient | None = None,
    ) -> Gtk.Widget: ...

class GradientChooserClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class HintBox(Gtk.Box):
    @classmethod
    def new(cls, hint: str) -> Gtk.Widget: ...

class HintBoxClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

ICON_APPLICATION_EXIT: str = "application-exit"
ICON_ASPECT_LANDSCAPE: str = "gimp-landscape"
ICON_ASPECT_PORTRAIT: str = "gimp-portrait"
ICON_ATTACH: str = "gimp-attach"
ICON_BUSINESS_CARD: str = "gimp-business-card"
ICON_CAP_BUTT: str = "gimp-cap-butt"
ICON_CAP_ROUND: str = "gimp-cap-round"
ICON_CAP_SQUARE: str = "gimp-cap-square"
ICON_CENTER: str = "gimp-center"
ICON_CENTER_HORIZONTAL: str = "gimp-hcenter"
ICON_CENTER_VERTICAL: str = "gimp-vcenter"
ICON_CHAIN_HORIZONTAL: str = "gimp-hchain"
ICON_CHAIN_HORIZONTAL_BROKEN: str = "gimp-hchain-broken"
ICON_CHAIN_VERTICAL: str = "gimp-vchain"
ICON_CHAIN_VERTICAL_BROKEN: str = "gimp-vchain-broken"
ICON_CHANNEL: str = "gimp-channel"
ICON_CHANNEL_ALPHA: str = "gimp-channel-alpha"
ICON_CHANNEL_BLUE: str = "gimp-channel-blue"
ICON_CHANNEL_GRAY: str = "gimp-channel-gray"
ICON_CHANNEL_GREEN: str = "gimp-channel-green"
ICON_CHANNEL_INDEXED: str = "gimp-channel-indexed"
ICON_CHANNEL_RED: str = "gimp-channel-red"
ICON_CHAR_PICKER: str = "gimp-char-picker"
ICON_CLOSE: str = "gimp-close"
ICON_CLOSE_ALL: str = "gimp-close-all"
ICON_COLORMAP: str = "gimp-colormap"
ICON_COLORS_DEFAULT: str = "gimp-default-colors"
ICON_COLORS_SWAP: str = "gimp-swap-colors"
ICON_COLOR_PICKER_BLACK: str = "gimp-color-picker-black"
ICON_COLOR_PICKER_GRAY: str = "gimp-color-picker-gray"
ICON_COLOR_PICKER_WHITE: str = "gimp-color-picker-white"
ICON_COLOR_PICK_FROM_SCREEN: str = "gimp-color-pick-from-screen"
ICON_COLOR_SELECTOR_CMYK: str = "gimp-color-cmyk"
ICON_COLOR_SELECTOR_TRIANGLE: str = "gimp-color-triangle"
ICON_COLOR_SELECTOR_WATER: str = "gimp-color-water"
ICON_COLOR_SPACE_LINEAR: str = "gimp-color-space-linear"
ICON_COLOR_SPACE_NON_LINEAR: str = "gimp-color-space-non-linear"
ICON_COLOR_SPACE_PERCEPTUAL: str = "gimp-color-space-perceptual"
ICON_CONTROLLER: str = "gimp-controller"
ICON_CONTROLLER_KEYBOARD: str = "gimp-controller-keyboard"
ICON_CONTROLLER_LINUX_INPUT: str = "gimp-controller-linux-input"
ICON_CONTROLLER_MIDI: str = "gimp-controller-midi"
ICON_CONTROLLER_WHEEL: str = "gimp-controller-wheel"
ICON_CONVERT_GRAYSCALE: str = "gimp-convert-grayscale"
ICON_CONVERT_INDEXED: str = "gimp-convert-indexed"
ICON_CONVERT_RGB: str = "gimp-convert-rgb"
ICON_CURSOR: str = "gimp-cursor"
ICON_CURVE_FREE: str = "gimp-curve-free"
ICON_CURVE_SMOOTH: str = "gimp-curve-smooth"
ICON_DETACH: str = "gimp-detach"
ICON_DIALOG_CHANNELS: str = "gimp-channels"
ICON_DIALOG_DASHBOARD: str = "gimp-dashboard"
ICON_DIALOG_DEVICE_STATUS: str = "gimp-device-status"
ICON_DIALOG_ERROR: str = "dialog-error"
ICON_DIALOG_IMAGES: str = "gimp-images"
ICON_DIALOG_INFORMATION: str = "dialog-information"
ICON_DIALOG_LAYERS: str = "gimp-layers"
ICON_DIALOG_NAVIGATION: str = "gimp-navigation"
ICON_DIALOG_PATHS: str = "gimp-paths"
ICON_DIALOG_QUESTION: str = "dialog-question"
ICON_DIALOG_RESHOW_FILTER: str = "gimp-reshow-filter"
ICON_DIALOG_TOOLS: str = "gimp-tools"
ICON_DIALOG_TOOL_OPTIONS: str = "gimp-tool-options"
ICON_DIALOG_UNDO_HISTORY: str = "gimp-undo-history"
ICON_DIALOG_WARNING: str = "dialog-warning"
ICON_DISPLAY: str = "gimp-display"
ICON_DISPLAY_FILTER: str = "gimp-display-filter"
ICON_DISPLAY_FILTER_CLIP_WARNING: str = "gimp-display-filter-clip-warning"
ICON_DISPLAY_FILTER_COLORBLIND: str = "gimp-display-filter-colorblind"
ICON_DISPLAY_FILTER_CONTRAST: str = "gimp-display-filter-contrast"
ICON_DISPLAY_FILTER_GAMMA: str = "gimp-display-filter-gamma"
ICON_DISPLAY_FILTER_LCMS: str = "gimp-display-filter-lcms"
ICON_DISPLAY_FILTER_PROOF: str = "gimp-display-filter-proof"
ICON_DOCUMENT_NEW: str = "document-new"
ICON_DOCUMENT_OPEN: str = "document-open"
ICON_DOCUMENT_OPEN_RECENT: str = "document-open-recent"
ICON_DOCUMENT_PAGE_SETUP: str = "document-page-setup"
ICON_DOCUMENT_PRINT: str = "document-print"
ICON_DOCUMENT_PRINT_RESOLUTION: str = "document-print"
ICON_DOCUMENT_PROPERTIES: str = "document-properties"
ICON_DOCUMENT_REVERT: str = "document-revert"
ICON_DOCUMENT_SAVE: str = "document-save"
ICON_DOCUMENT_SAVE_AS: str = "document-save-as"
ICON_DYNAMICS: str = "gimp-dynamics"
ICON_EDIT: str = "gtk-edit"
ICON_EDIT_CLEAR: str = "edit-clear"
ICON_EDIT_COPY: str = "edit-copy"
ICON_EDIT_CUT: str = "edit-cut"
ICON_EDIT_DELETE: str = "edit-delete"
ICON_EDIT_FIND: str = "edit-find"
ICON_EDIT_PASTE: str = "edit-paste"
ICON_EDIT_PASTE_AS_NEW: str = "gimp-paste-as-new"
ICON_EDIT_PASTE_INTO: str = "gimp-paste-into"
ICON_EDIT_REDO: str = "edit-redo"
ICON_EDIT_UNDO: str = "edit-undo"
ICON_EFFECT: str = "gimp-effects"
ICON_EVEN_HORIZONTAL_GAP: str = "gimp-even-horizontal-gap"
ICON_EVEN_VERTICAL_GAP: str = "gimp-even-vertical-gap"
ICON_FILE_MANAGER: str = "gimp-file-manager"
ICON_FILL_HORIZONTAL: str = "gimp-hfill"
ICON_FILL_VERTICAL: str = "gimp-vfill"
ICON_FOLDER_NEW: str = "folder-new"
ICON_FONT: str = "gtk-select-font"
ICON_FORMAT_INDENT_LESS: str = "format-indent-less"
ICON_FORMAT_INDENT_MORE: str = "format-indent-more"
ICON_FORMAT_JUSTIFY_CENTER: str = "format-justify-center"
ICON_FORMAT_JUSTIFY_FILL: str = "format-justify-fill"
ICON_FORMAT_JUSTIFY_LEFT: str = "format-justify-left"
ICON_FORMAT_JUSTIFY_RIGHT: str = "format-justify-right"
ICON_FORMAT_TEXT_BOLD: str = "format-text-bold"
ICON_FORMAT_TEXT_DIRECTION_LTR: str = "format-text-direction-ltr"
ICON_FORMAT_TEXT_DIRECTION_RTL: str = "format-text-direction-rtl"
ICON_FORMAT_TEXT_DIRECTION_TTB_LTR: str = "gimp-text-dir-ttb-ltr"
ICON_FORMAT_TEXT_DIRECTION_TTB_LTR_UPRIGHT: str = "gimp-text-dir-ttb-ltr-upright"
ICON_FORMAT_TEXT_DIRECTION_TTB_RTL: str = "gimp-text-dir-ttb-rtl"
ICON_FORMAT_TEXT_DIRECTION_TTB_RTL_UPRIGHT: str = "gimp-text-dir-ttb-rtl-upright"
ICON_FORMAT_TEXT_ITALIC: str = "format-text-italic"
ICON_FORMAT_TEXT_SPACING_LETTER: str = "gimp-letter-spacing"
ICON_FORMAT_TEXT_SPACING_LINE: str = "gimp-line-spacing"
ICON_FORMAT_TEXT_STRIKETHROUGH: str = "format-text-strikethrough"
ICON_FORMAT_TEXT_UNDERLINE: str = "format-text-underline"
ICON_FRAME: str = "gimp-frame"
ICON_GEGL: str = "gimp-gegl"
ICON_GO_BOTTOM: str = "go-bottom"
ICON_GO_DOWN: str = "go-down"
ICON_GO_FIRST: str = "go-first"
ICON_GO_HOME: str = "go-home"
ICON_GO_LAST: str = "go-last"
ICON_GO_NEXT: str = "go-next"
ICON_GO_PREVIOUS: str = "go-previous"
ICON_GO_TOP: str = "go-top"
ICON_GO_UP: str = "go-up"
ICON_GRADIENT_BILINEAR: str = "gimp-gradient-bilinear"
ICON_GRADIENT_CONICAL_ASYMMETRIC: str = "gimp-gradient-conical-asymmetric"
ICON_GRADIENT_CONICAL_SYMMETRIC: str = "gimp-gradient-conical-symmetric"
ICON_GRADIENT_LINEAR: str = "gimp-gradient-linear"
ICON_GRADIENT_RADIAL: str = "gimp-gradient-radial"
ICON_GRADIENT_SHAPEBURST_ANGULAR: str = "gimp-gradient-shapeburst-angular"
ICON_GRADIENT_SHAPEBURST_DIMPLED: str = "gimp-gradient-shapeburst-dimpled"
ICON_GRADIENT_SHAPEBURST_SPHERICAL: str = "gimp-gradient-shapeburst-spherical"
ICON_GRADIENT_SPIRAL_ANTICLOCKWISE: str = "gimp-gradient-spiral-anticlockwise"
ICON_GRADIENT_SPIRAL_CLOCKWISE: str = "gimp-gradient-spiral-clockwise"
ICON_GRADIENT_SQUARE: str = "gimp-gradient-square"
ICON_GRAVITY_EAST: str = "gimp-gravity-east"
ICON_GRAVITY_NORTH: str = "gimp-gravity-north"
ICON_GRAVITY_NORTH_EAST: str = "gimp-gravity-north-east"
ICON_GRAVITY_NORTH_WEST: str = "gimp-gravity-north-west"
ICON_GRAVITY_SOUTH: str = "gimp-gravity-south"
ICON_GRAVITY_SOUTH_EAST: str = "gimp-gravity-south-east"
ICON_GRAVITY_SOUTH_WEST: str = "gimp-gravity-south-west"
ICON_GRAVITY_WEST: str = "gimp-gravity-west"
ICON_GRID: str = "gimp-grid"
ICON_HELP: str = "system-help"
ICON_HELP_ABOUT: str = "help-about"
ICON_HELP_USER_MANUAL: str = "gimp-user-manual"
ICON_HISTOGRAM: str = "gimp-histogram"
ICON_HISTOGRAM_LINEAR: str = "gimp-histogram-linear"
ICON_HISTOGRAM_LOGARITHMIC: str = "gimp-histogram-logarithmic"
ICON_IMAGE: str = "gimp-image"
ICON_IMAGE_OPEN: str = "gimp-image-open"
ICON_IMAGE_RELOAD: str = "gimp-image-reload"
ICON_INPUT_DEVICE: str = "gimp-input-device"
ICON_INVERT: str = "gimp-invert"
ICON_JOIN_BEVEL: str = "gimp-join-bevel"
ICON_JOIN_MITER: str = "gimp-join-miter"
ICON_JOIN_ROUND: str = "gimp-join-round"
ICON_LAYER: str = "gimp-layer"
ICON_LAYER_ANCHOR: str = "gimp-anchor"
ICON_LAYER_FLOATING_SELECTION: str = "gimp-floating-selection"
ICON_LAYER_LINK_LAYER: str = "emblem-symbolic-link"
ICON_LAYER_MASK: str = "gimp-layer-mask"
ICON_LAYER_MERGE_DOWN: str = "gimp-merge-down"
ICON_LAYER_TEXT_LAYER: str = "gimp-text-layer"
ICON_LAYER_TO_IMAGESIZE: str = "gimp-layer-to-imagesize"
ICON_LAYER_VECTOR_LAYER: str = "gimp-tool-path"
ICON_LINKED: str = "gimp-linked"
ICON_LIST: str = "gimp-list"
ICON_LIST_ADD: str = "list-add"
ICON_LIST_REMOVE: str = "list-remove"
ICON_LOCK: str = "gimp-lock"
ICON_LOCK_ALPHA: str = "gimp-lock-alpha"
ICON_LOCK_CONTENT: str = "gimp-lock-content"
ICON_LOCK_MULTI: str = "gimp-lock-multi"
ICON_LOCK_PATH: str = "gimp-lock-path"
ICON_LOCK_POSITION: str = "gimp-lock-position"
ICON_LOCK_VISIBILITY: str = "gimp-lock-visibility"
ICON_MARKER: str = "gimp-marker"
ICON_MENU_LEFT: str = "gimp-menu-left"
ICON_MENU_RIGHT: str = "gimp-menu-right"
ICON_OBJECT_DUPLICATE: str = "gimp-duplicate"
ICON_OBJECT_FLIP_HORIZONTAL: str = "object-flip-horizontal"
ICON_OBJECT_FLIP_VERTICAL: str = "object-flip-vertical"
ICON_OBJECT_RESIZE: str = "gimp-resize"
ICON_OBJECT_ROTATE_180: str = "gimp-rotate-180"
ICON_OBJECT_ROTATE_270: str = "object-rotate-left"
ICON_OBJECT_ROTATE_90: str = "object-rotate-right"
ICON_OBJECT_SCALE: str = "gimp-scale"
ICON_PALETTE: str = "gtk-select-color"
ICON_PATH: str = "gimp-path"
ICON_PATH_STROKE: str = "gimp-path-stroke"
ICON_PATTERN: str = "gimp-pattern"
ICON_PIVOT_CENTER: str = "gimp-pivot-center"
ICON_PIVOT_EAST: str = "gimp-pivot-east"
ICON_PIVOT_NORTH: str = "gimp-pivot-north"
ICON_PIVOT_NORTH_EAST: str = "gimp-pivot-north-east"
ICON_PIVOT_NORTH_WEST: str = "gimp-pivot-north-west"
ICON_PIVOT_SOUTH: str = "gimp-pivot-south"
ICON_PIVOT_SOUTH_EAST: str = "gimp-pivot-south-east"
ICON_PIVOT_SOUTH_WEST: str = "gimp-pivot-south-west"
ICON_PIVOT_WEST: str = "gimp-pivot-west"
ICON_PLUGIN: str = "gimp-plugin"
ICON_PREFERENCES_SYSTEM: str = "preferences-system"
ICON_PROCESS_STOP: str = "process-stop"
ICON_QUICK_MASK_OFF: str = "gimp-quick-mask-off"
ICON_QUICK_MASK_ON: str = "gimp-quick-mask-on"
ICON_RECORD: str = "media-record"
ICON_RESET: str = "gimp-reset"
ICON_SAMPLE_POINT: str = "gimp-sample-point"
ICON_SELECTION: str = "gimp-selection"
ICON_SELECTION_ADD: str = "gimp-selection-add"
ICON_SELECTION_ALL: str = "gimp-selection-all"
ICON_SELECTION_BORDER: str = "gimp-selection-border"
ICON_SELECTION_GROW: str = "gimp-selection-grow"
ICON_SELECTION_INTERSECT: str = "gimp-selection-intersect"
ICON_SELECTION_NONE: str = "gimp-selection-none"
ICON_SELECTION_REPLACE: str = "gimp-selection-replace"
ICON_SELECTION_SHRINK: str = "gimp-selection-shrink"
ICON_SELECTION_STROKE: str = "gimp-selection-stroke"
ICON_SELECTION_SUBTRACT: str = "gimp-selection-subtract"
ICON_SELECTION_TO_CHANNEL: str = "gimp-selection-to-channel"
ICON_SELECTION_TO_PATH: str = "gimp-selection-to-path"
ICON_SHAPE_CIRCLE: str = "gimp-shape-circle"
ICON_SHAPE_DIAMOND: str = "gimp-shape-diamond"
ICON_SHAPE_SQUARE: str = "gimp-shape-square"
ICON_SHRED: str = "gimp-shred"
ICON_SMARTPHONE: str = "gimp-smartphone"
ICON_SYMMETRY: str = "gimp-symmetry"
ICON_SYSTEM_RUN: str = "system-run"
ICON_TEMPLATE: str = "gimp-template"
ICON_TEXTURE: str = "gimp-texture"
ICON_TOOL_AIRBRUSH: str = "gimp-tool-airbrush"
ICON_TOOL_ALIGN: str = "gimp-tool-align"
ICON_TOOL_BLUR: str = "gimp-tool-blur"
ICON_TOOL_BRIGHTNESS_CONTRAST: str = "gimp-tool-brightness-contrast"
ICON_TOOL_BUCKET_FILL: str = "gimp-tool-bucket-fill"
ICON_TOOL_BY_COLOR_SELECT: str = "gimp-tool-by-color-select"
ICON_TOOL_CAGE: str = "gimp-tool-cage"
ICON_TOOL_CLONE: str = "gimp-tool-clone"
ICON_TOOL_COLORIZE: str = "gimp-tool-colorize"
ICON_TOOL_COLOR_BALANCE: str = "gimp-tool-color-balance"
ICON_TOOL_COLOR_PICKER: str = "gimp-tool-color-picker"
ICON_TOOL_COLOR_TEMPERATURE: str = "gimp-tool-color-temperature"
ICON_TOOL_CROP: str = "gimp-tool-crop"
ICON_TOOL_CURVES: str = "gimp-tool-curves"
ICON_TOOL_DESATURATE: str = "gimp-tool-desaturate"
ICON_TOOL_DODGE: str = "gimp-tool-dodge"
ICON_TOOL_ELLIPSE_SELECT: str = "gimp-tool-ellipse-select"
ICON_TOOL_ERASER: str = "gimp-tool-eraser"
ICON_TOOL_EXPOSURE: str = "gimp-tool-exposure"
ICON_TOOL_FLIP: str = "gimp-tool-flip"
ICON_TOOL_FOREGROUND_SELECT: str = "gimp-tool-foreground-select"
ICON_TOOL_FREE_SELECT: str = "gimp-tool-free-select"
ICON_TOOL_FUZZY_SELECT: str = "gimp-tool-fuzzy-select"
ICON_TOOL_GRADIENT: str = "gimp-tool-gradient"
ICON_TOOL_HANDLE_TRANSFORM: str = "gimp-tool-handle-transform"
ICON_TOOL_HEAL: str = "gimp-tool-heal"
ICON_TOOL_HUE_SATURATION: str = "gimp-tool-hue-saturation"
ICON_TOOL_INK: str = "gimp-tool-ink"
ICON_TOOL_ISCISSORS: str = "gimp-tool-iscissors"
ICON_TOOL_LEVELS: str = "gimp-tool-levels"
ICON_TOOL_MEASURE: str = "gimp-tool-measure"
ICON_TOOL_MOVE: str = "gimp-tool-move"
ICON_TOOL_MYPAINT_BRUSH: str = "gimp-tool-mypaint-brush"
ICON_TOOL_N_POINT_DEFORMATION: str = "gimp-tool-n-point-deformation"
ICON_TOOL_OFFSET: str = "gimp-tool-offset"
ICON_TOOL_PAINTBRUSH: str = "gimp-tool-paintbrush"
ICON_TOOL_PAINT_SELECT: str = "gimp-tool-paint-select"
ICON_TOOL_PATH: str = "gimp-tool-path"
ICON_TOOL_PENCIL: str = "gimp-tool-pencil"
ICON_TOOL_PERSPECTIVE: str = "gimp-tool-perspective"
ICON_TOOL_PERSPECTIVE_CLONE: str = "gimp-tool-perspective-clone"
ICON_TOOL_POSTERIZE: str = "gimp-tool-posterize"
ICON_TOOL_PRESET: str = "gimp-tool-preset"
ICON_TOOL_RECT_SELECT: str = "gimp-tool-rect-select"
ICON_TOOL_ROTATE: str = "gimp-tool-rotate"
ICON_TOOL_SCALE: str = "gimp-tool-scale"
ICON_TOOL_SEAMLESS_CLONE: str = "gimp-tool-seamless-clone"
ICON_TOOL_SHADOWS_HIGHLIGHTS: str = "gimp-tool-shadows-highlights"
ICON_TOOL_SHEAR: str = "gimp-tool-shear"
ICON_TOOL_SMUDGE: str = "gimp-tool-smudge"
ICON_TOOL_TEXT: str = "gimp-tool-text"
ICON_TOOL_THRESHOLD: str = "gimp-tool-threshold"
ICON_TOOL_TRANSFORM_3D: str = "gimp-tool-transform-3d"
ICON_TOOL_UNIFIED_TRANSFORM: str = "gimp-tool-unified-transform"
ICON_TOOL_WARP: str = "gimp-tool-warp"
ICON_TOOL_ZOOM: str = "gimp-tool-zoom"
ICON_TRANSFORM_3D_CAMERA: str = "gimp-transform-3d-camera"
ICON_TRANSFORM_3D_MOVE: str = "gimp-transform-3d-move"
ICON_TRANSFORM_3D_ROTATE: str = "gimp-transform-3d-rotate"
ICON_TRANSPARENCY: str = "gimp-transparency"
ICON_VIDEO: str = "gimp-video"
ICON_VIEW_FULLSCREEN: str = "view-fullscreen"
ICON_VIEW_REFRESH: str = "view-refresh"
ICON_VIEW_SHRINK_WRAP: str = "view-shrink-wrap"
ICON_VIEW_ZOOM_FILL: str = "view-zoom-fill"
ICON_VISIBLE: str = "gimp-visible"
ICON_WEB: str = "gimp-web"
ICON_WILBER: str = "gimp-wilber"
ICON_WILBER_EEK: str = "gimp-wilber-eek"
ICON_WINDOW_CLOSE: str = "window-close"
ICON_WINDOW_MOVE_TO_SCREEN: str = "gimp-move-to-screen"
ICON_WINDOW_NEW: str = "window-new"
ICON_ZOOM_FIT_BEST: str = "zoom-fit-best"
ICON_ZOOM_FOLLOW_WINDOW: str = "gimp-zoom-follow-window"
ICON_ZOOM_IN: str = "zoom-in"
ICON_ZOOM_ORIGINAL: str = "zoom-original"
ICON_ZOOM_OUT: str = "zoom-out"

class ImageChooser(Gtk.Box):
    @classmethod
    def new(
        cls,
        title: str | None = None,
        label: str | None = None,
        image: Gimp.Image | None = None,
    ) -> Gtk.Widget: ...
    def get_image(self) -> Gimp.Image: ...
    def get_label(self) -> Gtk.Widget: ...
    def set_image(self, image: Gimp.Image) -> None: ...

class ImageChooserClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ImageComboBox(IntComboBox):
    @classmethod
    def new(
        cls, constraint: collections.abc.Callable[[Gimp.Image, Any], bool] | None = None
    ) -> Gtk.Widget: ...

class ImageComboBoxClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class IntComboBoxClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class IntComboBoxLayout(GObject.GEnum):
    ICON_ONLY = 0
    ABBREVIATED = 1
    FULL = 2

class IntRadioFrame(Frame):
    @classmethod
    def new(cls, labels: list[str]) -> Gtk.Widget: ...
    @classmethod
    def new_from_store(cls, title: str, store: IntStore) -> Gtk.Widget: ...
    def get_active(self) -> int: ...
    def get_active_user_data(self) -> tuple[bool, typing.Any | None]: ...
    def set_active(self, value: int) -> bool: ...
    def set_active_by_user_data(self, user_data: Any = None) -> bool: ...
    def set_sensitivity(
        self,
        func: collections.abc.Callable[[int, typing.Any, int, typing.Any], bool],
        data: Any = None,
    ) -> None: ...
    def set_title(self, title: str, with_mnemonic: bool) -> None: ...

class IntRadioFrameClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class IntStoreClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class IntStoreColumns(enum.IntEnum):
    VALUE = 0
    LABEL = 1
    ABBREV = 2
    ICON_NAME = 3
    PIXBUF = 4
    USER_DATA = 5
    NUM_COLUMNS = 6

class ItemChooser(Gtk.Box):
    @classmethod
    def new(
        cls,
        title: str | None,
        label: str | None,
        item_type: GObject.GType,
        item: Gimp.Item | None = None,
    ) -> Gtk.Widget: ...
    def get_item(self) -> Gimp.Item: ...
    def get_label(self) -> Gtk.Widget: ...
    def set_item(self, item: Gimp.Item) -> None: ...

class ItemChooserClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class LabelColor(Labeled):
    @classmethod
    def new(cls, label: str, color: Gegl.Color, editable: bool) -> Gtk.Widget: ...
    def get_color_widget(self) -> Gtk.Widget: ...
    def get_value(self) -> Gegl.Color: ...
    def is_editable(self) -> bool: ...
    def set_editable(self, editable: bool) -> None: ...
    def set_value(self, value: Gegl.Color) -> None: ...

class LabelColorClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class LabelEntry(Labeled):
    @classmethod
    def new(cls, label: str) -> Gtk.Widget: ...
    def get_entry(self) -> Gtk.Widget: ...
    def get_value(self) -> str: ...
    def set_value(self, value: str) -> None: ...

class LabelEntryClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class LabelIntWidget(Labeled):
    @classmethod
    def new(cls, text: str, widget: Gtk.Widget) -> Gtk.Widget: ...
    def get_widget(self) -> Gtk.Widget: ...

class LabelIntWidgetClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class LabelSpinClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def value_changed(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class LabelStringWidget(Labeled):
    @classmethod
    def new(cls, text: str, widget: Gtk.Widget) -> Gtk.Widget: ...
    def get_widget(self) -> Gtk.Widget: ...

class LabelStringWidgetClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class LabeledClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def mnemonic_widget_changed(self) -> Any: ...
    @property
    def populate(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class LayerComboBox(IntComboBox):
    @classmethod
    def new(
        cls,
        constraint: collections.abc.Callable[[Gimp.Image, Gimp.Item, Any], bool]
        | None = None,
    ) -> Gtk.Widget: ...

class MemsizeEntry(Gtk.Box):
    @classmethod
    def new(cls, value: int, lower: int, upper: int) -> Gtk.Widget: ...
    def get_spinbutton(self) -> Gtk.SpinButton: ...
    def get_value(self) -> int: ...
    def set_value(self, value: int) -> None: ...

class MemsizeEntryClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class NumberPairEntry(Gtk.Entry):
    @classmethod
    def new(
        cls,
        separators: str,
        allow_simplification: bool,
        min_valid_value: float,
        max_valid_value: float,
    ) -> Gtk.Widget: ...
    def get_aspect(self) -> AspectType: ...
    def get_default_text(self) -> str | None: ...
    def get_default_values(self) -> tuple[float, float]: ...
    def get_ratio(self) -> float: ...
    def get_user_override(self) -> bool: ...
    def get_values(self) -> tuple[float, float]: ...
    def set_aspect(self, aspect: AspectType) -> None: ...
    def set_default_text(self, string: str) -> None: ...
    def set_default_values(self, left: float, right: float) -> None: ...
    def set_ratio(self, ratio: float) -> None: ...
    def set_user_override(self, user_override: bool) -> None: ...
    def set_values(self, left: float, right: float) -> None: ...

class NumberPairEntryClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class OffsetArea(Gtk.DrawingArea):
    @classmethod
    def new(cls, orig_width: int, orig_height: int) -> Gtk.Widget: ...
    def set_offsets(self, offset_x: int, offset_y: int) -> None: ...
    def set_pixbuf(self, pixbuf: GdkPixbuf.Pixbuf) -> None: ...
    def set_size(self, width: int, height: int) -> None: ...

class OffsetAreaClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class PageSelector(Gtk.Box):
    @classmethod
    def new(cls) -> Gtk.Widget: ...
    def get_n_pages(self) -> int: ...
    def get_page_label(self, page_no: int) -> str | None: ...
    def get_page_thumbnail(self, page_no: int) -> GdkPixbuf.Pixbuf | None: ...
    def get_selected_pages(self) -> list[int]: ...
    def get_selected_range(self) -> str: ...
    def get_target(self) -> PageSelectorTarget: ...
    def page_is_selected(self, page_no: int) -> bool: ...
    def select_all(self) -> None: ...
    def select_page(self, page_no: int) -> None: ...
    def select_range(self, range: str) -> None: ...
    def set_n_pages(self, n_pages: int) -> None: ...
    def set_page_label(self, page_no: int, label: str) -> None: ...
    def set_page_thumbnail(self, page_no: int, thumbnail: GdkPixbuf.Pixbuf) -> None: ...
    def set_target(self, target: PageSelectorTarget) -> None: ...
    def unselect_all(self) -> None: ...
    def unselect_page(self, page_no: int) -> None: ...

class PageSelectorClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class PageSelectorTarget(GObject.GEnum):
    LAYERS = 0
    IMAGES = 1

class PaletteChooser(ResourceChooser):
    @classmethod
    def new(
        cls,
        title: str | None = None,
        label: str | None = None,
        palette: Gimp.Palette | None = None,
    ) -> Gtk.Widget: ...

class PaletteChooserClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class PathComboBox(IntComboBox):
    @classmethod
    def new(
        cls,
        constraint: collections.abc.Callable[[Gimp.Image, Gimp.Item, Any], bool]
        | None = None,
    ) -> Gtk.Widget: ...

class PathEditor(Gtk.Box):
    @classmethod
    def new(cls, title: str, path: str | None = None) -> Gtk.Widget: ...
    def get_dir_writable(self, directory: str) -> bool: ...
    def get_path(self) -> str: ...
    def get_writable_path(self) -> str: ...
    def set_dir_writable(self, directory: str, writable: bool) -> None: ...
    def set_path(self, path: str) -> None: ...
    def set_writable_path(self, path: str) -> None: ...

class PathEditorClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class PatternChooser(ResourceChooser):
    @classmethod
    def new(
        cls,
        title: str | None = None,
        label: str | None = None,
        pattern: Gimp.Pattern | None = None,
    ) -> Gtk.Widget: ...

class PatternChooserClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class PickButton(Gtk.Button):
    @classmethod
    def new(cls) -> Gtk.Widget: ...
    def do_color_picked(type, self, color: Gegl.Color) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class PickButtonClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def color_picked(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class PreviewArea(Gtk.DrawingArea):
    @classmethod
    def new(cls) -> Gtk.Widget: ...
    def blend(
        self,
        x: int,
        y: int,
        width: int,
        height: int,
        type: Gimp.ImageType,
        buf1: list[int],
        rowstride1: int,
        buf2: list[int],
        rowstride2: int,
        opacity: int,
    ) -> None: ...
    def draw(
        self,
        x: int,
        y: int,
        width: int,
        height: int,
        type: Gimp.ImageType,
        buf: list[int],
        rowstride: int,
    ) -> None: ...
    def fill(
        self, x: int, y: int, width: int, height: int, red: int, green: int, blue: int
    ) -> None: ...
    def get_size(self) -> tuple[int, int]: ...
    def mask(
        self,
        x: int,
        y: int,
        width: int,
        height: int,
        type: Gimp.ImageType,
        buf1: list[int],
        rowstride1: int,
        buf2: list[int],
        rowstride2: int,
        mask: list[int],
        rowstride_mask: int,
    ) -> None: ...
    def menu_popup(self, event: Gdk.EventButton | None = None) -> None: ...
    def reset(self) -> None: ...
    def set_color_config(self, config: Gimp.ColorConfig) -> None: ...
    def set_colormap(self, colormap: list[int], num_colors: int) -> None: ...
    def set_max_size(self, width: int, height: int) -> None: ...
    def set_offsets(self, x: int, y: int) -> None: ...

class PreviewAreaClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class PreviewClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def draw(self) -> Any: ...
    @property
    def draw_thumb(self) -> Any: ...
    @property
    def draw_buffer(self) -> Any: ...
    @property
    def set_cursor(self) -> Any: ...
    @property
    def transform(self) -> Any: ...
    @property
    def untransform(self) -> Any: ...
    @property
    def invalidated(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class ProcBrowserDialog(Dialog):
    def get_selected(self) -> str | None: ...

class ProcBrowserDialogClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ProcedureDialogClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def fill_start(self) -> Any: ...
    @property
    def fill_end(self) -> Any: ...
    @property
    def fill_list(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class ProgressBar(Gtk.ProgressBar):
    @classmethod
    def new(cls) -> Gtk.Widget: ...

class ProgressBarClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ResourceChooserClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def resource_set(self) -> Any: ...
    @property
    def draw_interior(self) -> Any: ...
    @property
    def resource_type(self) -> Any: ...
    @property
    def padding(self) -> Any: ...

class Ruler(Gtk.Widget):
    @classmethod
    def new(cls, orientation: Gtk.Orientation) -> Gtk.Widget: ...
    def add_track_widget(self, widget: Gtk.Widget) -> None: ...
    def get_position(self) -> float: ...
    def get_range(self) -> tuple[float, float, float]: ...
    def get_unit(self) -> Gimp.Unit: ...
    def remove_track_widget(self, widget: Gtk.Widget) -> None: ...
    def set_position(self, position: float) -> None: ...
    def set_range(self, lower: float, upper: float, max_size: float) -> None: ...
    def set_unit(self, unit: Gimp.Unit) -> None: ...

class RulerClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ScaleEntryClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def new_range_widget(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class ScrolledPreviewClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class SizeEntry(Gtk.Grid):
    @classmethod
    def new(
        cls,
        number_of_fields: int,
        unit: Gimp.Unit,
        unit_format: str,
        menu_show_pixels: bool,
        menu_show_percent: bool,
        show_refval: bool,
        spinbutton_width: int,
        update_policy: SizeEntryUpdatePolicy,
    ) -> Gtk.Widget: ...
    def add_field(
        self,
        value_spinbutton: Gtk.SpinButton,
        refval_spinbutton: Gtk.SpinButton | None = None,
    ) -> None: ...
    def attach_label(
        self, text: str, row: int, column: int, alignment: float
    ) -> Gtk.Widget: ...
    def get_help_widget(self, field: int) -> Gtk.Widget: ...
    def get_n_fields(self) -> int: ...
    def get_refval(self, field: int) -> float: ...
    def get_unit(self) -> Gimp.Unit: ...
    def get_unit_combo(self) -> UnitComboBox: ...
    def get_update_policy(self) -> SizeEntryUpdatePolicy: ...
    def get_value(self, field: int) -> float: ...
    def grab_focus(self) -> None: ...
    def set_activates_default(self, setting: bool) -> None: ...
    def set_pixel_digits(self, digits: int) -> None: ...
    def set_refval(self, field: int, refval: float) -> None: ...
    def set_refval_boundaries(self, field: int, lower: float, upper: float) -> None: ...
    def set_refval_digits(self, field: int, digits: int) -> None: ...
    def set_resolution(
        self, field: int, resolution: float, keep_size: bool
    ) -> None: ...
    def set_size(self, field: int, lower: float, upper: float) -> None: ...
    def set_unit(self, unit: Gimp.Unit) -> None: ...
    def set_value(self, field: int, value: float) -> None: ...
    def set_value_boundaries(self, field: int, lower: float, upper: float) -> None: ...
    def show_unit_menu(self, show: bool) -> None: ...

class SizeEntryClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class SizeEntryUpdatePolicy(GObject.GEnum):
    NONE = 0
    SIZE = 1
    RESOLUTION = 2

class SpinButton(Gtk.SpinButton):
    @classmethod
    def new(
        cls, adjustment: Gtk.Adjustment | None, climb_rate: float, digits: int
    ) -> Gtk.Widget: ...
    @classmethod
    def new_with_range(cls, min: float, max: float, step: float) -> Gtk.Widget: ...
    @property
    def parent_instance(self) -> Any: ...

class SpinButtonClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class SpinScale(SpinButton):
    @classmethod
    def new(cls, adjustment: Gtk.Adjustment, label: str, digits: int) -> Gtk.Widget: ...
    def get_constrain_drag(self) -> bool: ...
    def get_gamma(self) -> float: ...
    def get_label(self) -> str: ...
    def get_mnemonic_keyval(self) -> int: ...
    def get_scale_limits(self, lower: float, upper: float) -> bool: ...
    def set_constrain_drag(self, constrain: bool) -> None: ...
    def set_gamma(self, gamma: float) -> None: ...
    def set_label(self, label: str) -> None: ...
    def set_scale_limits(self, lower: float, upper: float) -> None: ...
    def unset_scale_limits(self) -> None: ...

class SpinScaleClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class StringComboBox(Gtk.ComboBox):
    @classmethod
    def new(
        cls, model: Gtk.TreeModel, id_column: int, label_column: int
    ) -> Gtk.Widget: ...
    def get_active(self) -> str: ...
    def set_active(self, id: str) -> bool: ...
    def set_sensitivity(
        self, func: collections.abc.Callable[[str, typing.Any], bool], data: Any = None
    ) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class StringComboBoxClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class UnitComboBox(Gtk.ComboBox):
    @classmethod
    def new(cls) -> Gtk.Widget: ...
    @classmethod
    def new_with_model(cls, model: UnitStore) -> Gtk.Widget: ...
    def get_active(self) -> Gimp.Unit: ...
    def set_active(self, unit: Gimp.Unit) -> None: ...

class UnitComboBoxClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class UnitStore(GObject.Object, Gtk.TreeModel):
    @classmethod
    def new(cls, num_values: int) -> UnitStore: ...
    def get_has_percent(self) -> bool: ...
    def get_has_pixels(self) -> bool: ...
    def get_nth_value(self, unit: Gimp.Unit, index: int) -> float: ...
    def set_has_percent(self, has_percent: bool) -> None: ...
    def set_has_pixels(self, has_pixels: bool) -> None: ...
    def set_pixel_value(self, index: int, value: float) -> None: ...
    def set_resolution(self, index: int, resolution: float) -> None: ...
    @property
    def parent_instance(self) -> Any: ...

class UnitStoreClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...
    @property
    def _gimp_reserved0(self) -> Any: ...
    @property
    def _gimp_reserved1(self) -> Any: ...
    @property
    def _gimp_reserved2(self) -> Any: ...
    @property
    def _gimp_reserved3(self) -> Any: ...
    @property
    def _gimp_reserved4(self) -> Any: ...
    @property
    def _gimp_reserved5(self) -> Any: ...
    @property
    def _gimp_reserved6(self) -> Any: ...
    @property
    def _gimp_reserved7(self) -> Any: ...
    @property
    def _gimp_reserved8(self) -> Any: ...
    @property
    def _gimp_reserved9(self) -> Any: ...

class VectorLoadProcedureDialog(ProcedureDialog):
    @classmethod
    def new(
        cls,
        procedure: Gimp.VectorLoadProcedure,
        config: Gimp.ProcedureConfig,
        extracted_data: Gimp.VectorLoadData | None = None,
        file: Gio.File | None = None,
    ) -> Gtk.Widget: ...

class VectorLoadProcedureDialogClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class WidgetsError(enum.IntEnum):
    WIDGETS_PARSE_ERROR = 0

class ZoomModel(GObject.Object):
    @classmethod
    def new(cls) -> ZoomModel: ...
    @staticmethod
    def zoom_step(zoom_type: ZoomType, scale: float, delta: float) -> float: ...
    def get_factor(self) -> float: ...
    def get_fraction(self) -> tuple[int, int]: ...
    def set_range(self, min: float, max: float) -> None: ...
    def zoom(self, zoom_type: ZoomType, scale: float) -> None: ...

class ZoomModelClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ZoomPreview(ScrolledPreview):
    @classmethod
    def new_from_drawable(cls, drawable: Gimp.Drawable) -> Gtk.Widget: ...
    @classmethod
    def new_with_model_from_drawable(
        cls, drawable: Gimp.Drawable, model: ZoomModel
    ) -> Gtk.Widget: ...
    def get_drawable(self) -> Gimp.Drawable: ...
    def get_factor(self) -> float: ...
    def get_model(self) -> ZoomModel: ...
    def get_source(self) -> tuple[list[int], int, int, int]: ...

class ZoomPreviewClass(gi.Struct):
    @property
    def parent_class(self) -> Any: ...

class ZoomType(GObject.GEnum):
    IN = 0
    OUT = 1

def cairo_set_focus_line_pattern(cr: cairo.Context, widget: Gtk.Widget) -> bool: ...
def cairo_set_source_color(
    cr: cairo.Context,
    color: Gegl.Color,
    config: Gimp.ColorConfig,
    softproof: bool,
    widget: Gtk.Widget | None = None,
) -> None: ...
def cairo_surface_create_from_pixbuf(pixbuf: GdkPixbuf.Pixbuf) -> cairo.Surface: ...
def context_help(widget: Gtk.Widget) -> None: ...
def coordinates_new(
    unit: Gimp.Unit,
    unit_format: str,
    menu_show_pixels: bool,
    menu_show_percent: bool,
    spinbutton_width: int,
    update_policy: SizeEntryUpdatePolicy,
    chainbutton_active: bool,
    chain_constrains_ratio: bool,
    xlabel: str,
    x: float,
    xres: float,
    lower_boundary_x: float,
    upper_boundary_x: float,
    xsize_0: float,
    xsize_100: float,
    ylabel: str,
    y: float,
    yres: float,
    lower_boundary_y: float,
    upper_boundary_y: float,
    ysize_0: float,
    ysize_100: float,
) -> Gtk.Widget: ...
def double_adjustment_update(adjustment: Gtk.Adjustment) -> float: ...
def enum_icon_box_new(
    enum_type: GObject.GType,
    icon_prefix: str,
    icon_size: Gtk.IconSize,
    callback: collections.abc.Callable[[], None] | None = None,
    callback_data: Any = None,
) -> tuple[Gtk.Widget, Gtk.Widget]: ...
def enum_icon_box_new_with_range(
    enum_type: GObject.GType,
    minimum: int,
    maximum: int,
    icon_prefix: str,
    icon_size: Gtk.IconSize,
    callback: collections.abc.Callable[[], None] | None = None,
    callback_data: Any = None,
) -> tuple[Gtk.Widget, Gtk.Widget]: ...
def enum_icon_box_set_child_padding(
    icon_box: Gtk.Widget, xpad: int, ypad: int
) -> None: ...
def enum_icon_box_set_icon_size(
    icon_box: Gtk.Widget, icon_size: Gtk.IconSize
) -> None: ...
def enum_radio_box_new(
    enum_type: GObject.GType,
    callback: collections.abc.Callable[[], None] | None = None,
    callback_data: Any = None,
) -> tuple[Gtk.Widget, Gtk.Widget]: ...
def enum_radio_box_new_with_range(
    enum_type: GObject.GType,
    minimum: int,
    maximum: int,
    callback: collections.abc.Callable[[], None] | None = None,
    callback_data: Any = None,
) -> tuple[Gtk.Widget, Gtk.Widget]: ...
def enum_radio_frame_new(
    enum_type: GObject.GType,
    label_widget: Gtk.Widget | None = None,
    callback: collections.abc.Callable[[], None] | None = None,
    callback_data: Any = None,
) -> tuple[Gtk.Widget, Gtk.Widget]: ...
def enum_radio_frame_new_with_range(
    enum_type: GObject.GType,
    minimum: int,
    maximum: int,
    label_widget: Gtk.Widget | None = None,
    callback: collections.abc.Callable[[], None] | None = None,
    callback_data: Any = None,
) -> tuple[Gtk.Widget, Gtk.Widget]: ...
def event_triggers_context_menu(event: Gdk.Event, on_release: bool) -> bool: ...
def float_adjustment_update(adjustment: Gtk.Adjustment) -> float: ...
def get_monitor_at_pointer() -> Gdk.Monitor: ...
def grid_attach_aligned(
    grid: Gtk.Grid,
    left: int,
    top: int,
    label_text: str,
    label_xalign: float,
    label_yalign: float,
    widget: Gtk.Widget,
    widget_columns: int,
) -> Gtk.Widget: ...
def help_connect(
    widget: Gtk.Widget,
    tooltip: str | None,
    help_func: collections.abc.Callable[[str, typing.Any], None],
    help_id: str,
    help_data: Any = None,
) -> None: ...
def help_id_quark() -> int: ...
def help_set_help_data(
    widget: Gtk.Widget, tooltip: str | None, help_id: str
) -> None: ...
def help_set_help_data_with_markup(
    widget: Gtk.Widget, tooltip: str, help_id: str
) -> None: ...
def icons_init() -> None: ...
def icons_set_icon_theme(path: Gio.File) -> bool: ...
def init(prog_name: str) -> None: ...
def int_adjustment_update(adjustment: Gtk.Adjustment) -> int: ...
def int_radio_group_set_active(
    radio_button: Gtk.RadioButton, item_data: int
) -> None: ...
def monitor_get_color_profile(monitor: Gdk.Monitor) -> Gimp.ColorProfile | None: ...
def proc_view_new(procedure_name: str) -> Gtk.Widget: ...
def prop_boolean_combo_box_new(
    config: GObject.Object, property_name: str, true_text: str, false_text: str
) -> Gtk.Widget: ...
def prop_boolean_radio_frame_new(
    config: GObject.Object,
    property_name: str,
    title: str | None,
    true_text: str,
    false_text: str,
) -> Gtk.Widget: ...
def prop_brush_chooser_new(
    config: GObject.Object, property_name: str, chooser_title: str | None = None
) -> Gtk.Widget: ...
def prop_check_button_new(
    config: GObject.Object, property_name: str, label: str | None = None
) -> Gtk.Widget: ...
def prop_choice_combo_box_new(
    config: GObject.Object, property_name: str
) -> Gtk.Widget: ...
def prop_choice_radio_frame_new(
    config: GObject.Object, property_name: str
) -> Gtk.Widget: ...
def prop_color_area_new(
    config: GObject.Object,
    property_name: str,
    width: int,
    height: int,
    type: ColorAreaType,
) -> Gtk.Widget: ...
def prop_color_select_new(
    config: GObject.Object,
    property_name: str,
    width: int,
    height: int,
    type: ColorAreaType,
) -> Gtk.Widget: ...
def prop_coordinates_connect(
    config: GObject.Object,
    x_property_name: str,
    y_property_name: str,
    unit_property_name: str,
    sizeentry: Gtk.Widget,
    chainbutton: Gtk.Widget,
    xresolution: float,
    yresolution: float,
) -> bool: ...
def prop_coordinates_new(
    config: GObject.Object,
    x_property_name: str,
    y_property_name: str,
    unit_property_name: str,
    unit_format: str,
    update_policy: SizeEntryUpdatePolicy,
    xresolution: float,
    yresolution: float,
    has_chainbutton: bool,
) -> Gtk.Widget: ...
def prop_drawable_chooser_new(
    config: GObject.Object, property_name: str, chooser_title: str | None = None
) -> Gtk.Widget: ...
def prop_entry_new(
    config: GObject.Object, property_name: str, max_len: int
) -> Gtk.Widget: ...
def prop_enum_check_button_new(
    config: GObject.Object,
    property_name: str,
    label: str | None,
    false_value: int,
    true_value: int,
) -> Gtk.Widget: ...
def prop_enum_combo_box_new(
    config: GObject.Object, property_name: str, minimum: int, maximum: int
) -> Gtk.Widget: ...
def prop_enum_icon_box_new(
    config: GObject.Object,
    property_name: str,
    icon_prefix: str,
    minimum: int,
    maximum: int,
) -> Gtk.Widget: ...
def prop_enum_label_new(config: GObject.Object, property_name: str) -> Gtk.Widget: ...
def prop_enum_radio_box_new(
    config: GObject.Object, property_name: str, minimum: int, maximum: int
) -> Gtk.Widget: ...
def prop_enum_radio_frame_new(
    config: GObject.Object,
    property_name: str,
    title: str | None,
    minimum: int,
    maximum: int,
) -> Gtk.Widget: ...
def prop_expander_new(
    config: GObject.Object, property_name: str, label: str | None = None
) -> Gtk.Widget: ...
def prop_file_chooser_button_new(
    config: GObject.Object,
    property_name: str,
    title: str | None,
    action: Gtk.FileChooserAction,
) -> Gtk.Widget: ...
def prop_file_chooser_button_new_with_dialog(
    config: GObject.Object, property_name: str, dialog: Gtk.Widget
) -> Gtk.Widget: ...
def prop_file_chooser_new(
    config: GObject.Object,
    property_name: str,
    label: str | None = None,
    title: str | None = None,
) -> Gtk.Widget: ...
def prop_font_chooser_new(
    config: GObject.Object, property_name: str, chooser_title: str | None = None
) -> Gtk.Widget: ...
def prop_gradient_chooser_new(
    config: GObject.Object, property_name: str, chooser_title: str | None = None
) -> Gtk.Widget: ...
def prop_hscale_new(
    config: GObject.Object,
    property_name: str,
    step_increment: float,
    page_increment: float,
    digits: int,
) -> Gtk.Widget: ...
def prop_icon_image_new(
    config: GObject.Object, property_name: str, icon_size: Gtk.IconSize
) -> Gtk.Widget: ...
def prop_image_chooser_new(
    config: GObject.Object, property_name: str, chooser_title: str | None = None
) -> Gtk.Widget: ...
def prop_int_combo_box_new(
    config: GObject.Object, property_name: str, store: IntStore
) -> Gtk.Widget: ...
def prop_int_radio_frame_new(
    config: GObject.Object, property_name: str, title: str | None, store: IntStore
) -> Gtk.Widget: ...
def prop_item_chooser_new(
    config: GObject.Object, property_name: str, chooser_title: str | None = None
) -> Gtk.Widget: ...
def prop_label_color_new(
    config: GObject.Object, property_name: str, editable: bool
) -> Gtk.Widget: ...
def prop_label_entry_new(
    config: GObject.Object, property_name: str, max_len: int
) -> Gtk.Widget: ...
def prop_label_new(config: GObject.Object, property_name: str) -> Gtk.Widget: ...
def prop_label_spin_new(
    config: GObject.Object, property_name: str, digits: int
) -> Gtk.Widget: ...
def prop_memsize_entry_new(
    config: GObject.Object, property_name: str
) -> Gtk.Widget: ...
def prop_palette_chooser_new(
    config: GObject.Object, property_name: str, chooser_title: str | None = None
) -> Gtk.Widget: ...
def prop_path_editor_new(
    config: GObject.Object,
    path_property_name: str,
    writable_property_name: str,
    filechooser_title: str,
) -> Gtk.Widget: ...
def prop_pattern_chooser_new(
    config: GObject.Object, property_name: str, chooser_title: str | None = None
) -> Gtk.Widget: ...
def prop_pointer_combo_box_new(
    config: GObject.Object, property_name: str, store: IntStore
) -> Gtk.Widget: ...
def prop_scale_entry_new(
    config: GObject.Object,
    property_name: str,
    label: str | None,
    factor: float,
    limit_scale: bool,
    lower_limit: float,
    upper_limit: float,
) -> Gtk.Widget: ...
def prop_size_entry_new(
    config: GObject.Object,
    property_name: str,
    property_is_pixel: bool,
    unit_property_name: str,
    unit_format: str,
    update_policy: SizeEntryUpdatePolicy,
    resolution: float,
) -> Gtk.Widget: ...
def prop_spin_button_new(
    config: GObject.Object,
    property_name: str,
    step_increment: float,
    page_increment: float,
    digits: int,
) -> Gtk.Widget: ...
def prop_spin_scale_new(
    config: GObject.Object,
    property_name: str,
    step_increment: float,
    page_increment: float,
    digits: int,
) -> Gtk.Widget: ...
def prop_string_combo_box_new(
    config: GObject.Object,
    property_name: str,
    model: Gtk.TreeModel,
    id_column: int,
    label_column: int,
) -> Gtk.Widget: ...
def prop_switch_new(
    config: GObject.Object, property_name: str, label: str
) -> tuple[Gtk.Widget, Gtk.Widget, Gtk.Widget]: ...
def prop_text_buffer_new(
    config: GObject.Object, property_name: str, max_len: int
) -> Gtk.TextBuffer: ...
def prop_toggle_new(
    config: GObject.Object, property_name: str, icon_name: str, label: str
) -> tuple[Gtk.Widget, Gtk.Widget]: ...
def prop_unit_combo_box_new(
    config: GObject.Object, property_name: str
) -> Gtk.Widget: ...
def prop_widget_set_factor(
    widget: Gtk.Widget,
    factor: float,
    step_increment: float,
    page_increment: float,
    digits: int,
) -> None: ...
def query_boolean_box(
    title: str,
    parent: Gtk.Widget,
    help_func: collections.abc.Callable[[str, typing.Any], None],
    help_id: str,
    icon_name: str,
    message: str,
    true_button: str,
    false_button: str,
    object: GObject.Object,
    signal: str,
    callback: collections.abc.Callable[[Gtk.Widget, bool, typing.Any], None],
    data: Any = None,
) -> Gtk.Widget: ...
def query_double_box(
    title: str,
    parent: Gtk.Widget,
    help_func: collections.abc.Callable[[str, typing.Any], None],
    help_id: str,
    message: str,
    initial: float,
    lower: float,
    upper: float,
    digits: int,
    object: GObject.Object,
    signal: str,
    callback: collections.abc.Callable[[Gtk.Widget, float, typing.Any], None],
    data: Any = None,
) -> Gtk.Widget: ...
def query_int_box(
    title: str,
    parent: Gtk.Widget,
    help_func: collections.abc.Callable[[str, typing.Any], None],
    help_id: str,
    message: str,
    initial: int,
    lower: int,
    upper: int,
    object: GObject.Object,
    signal: str,
    callback: collections.abc.Callable[[Gtk.Widget, int, typing.Any], None],
    data: Any = None,
) -> Gtk.Widget: ...
def query_size_box(
    title: str,
    parent: Gtk.Widget,
    help_func: collections.abc.Callable[[str, typing.Any], None],
    help_id: str,
    message: str,
    initial: float,
    lower: float,
    upper: float,
    digits: int,
    unit: Gimp.Unit,
    resolution: float,
    dot_for_dot: bool,
    object: GObject.Object,
    signal: str,
    callback: collections.abc.Callable[
        [Gtk.Widget, float, Gimp.Unit, typing.Any], None
    ],
    data: Any = None,
) -> Gtk.Widget: ...
def query_string_box(
    title: str,
    parent: Gtk.Widget,
    help_func: collections.abc.Callable[[str, typing.Any], None],
    help_id: str,
    message: str,
    initial: str,
    object: GObject.Object,
    signal: str,
    callback: collections.abc.Callable[[Gtk.Widget, str, typing.Any], None],
    data: Any = None,
) -> Gtk.Widget: ...
def radio_button_update(widget: Gtk.Widget) -> int: ...
def random_seed_new(seed: int, random_seed: bool) -> Gtk.Widget: ...
def scroll_adjustment_values(
    sevent: Gdk.EventScroll,
    hadj: Gtk.Adjustment | None = None,
    vadj: Gtk.Adjustment | None = None,
) -> tuple[float, float]: ...
def standard_help_func(help_id: str, help_data: Any = None) -> None: ...
def toggle_button_update(widget: Gtk.Widget) -> bool: ...
def uint_adjustment_update(adjustment: Gtk.Adjustment) -> int: ...
def widget_animation_enabled() -> bool: ...
def widget_free_native_handle(
    widget: Gtk.Widget, window_handle: GLib.Bytes
) -> GLib.Bytes: ...
def widget_get_color_profile(widget: Gtk.Widget) -> Gimp.ColorProfile | None: ...
def widget_get_color_transform(
    widget: Gtk.Widget,
    config: Gimp.ColorConfig,
    src_profile: Gimp.ColorProfile,
    src_format: Babl.Object,
    dest_format: Babl.Object,
    softproof_profile: Gimp.ColorProfile,
    proof_intent: Gimp.ColorRenderingIntent,
    proof_bpc: bool,
) -> Gimp.ColorTransform | None: ...
def widget_get_monitor(widget: Gtk.Widget) -> Gdk.Monitor: ...
def widget_get_render_space(
    widget: Gtk.Widget, config: Gimp.ColorConfig
) -> Babl.Object: ...
def widget_set_native_handle(
    widget: Gtk.Widget, window_handle: GLib.Bytes
) -> GLib.Bytes: ...
def widget_track_monitor(
    widget: Gtk.Widget,
    monitor_changed_callback: collections.abc.Callable[[], None],
    user_data: Any = None,
) -> None: ...
def widgets_error_quark() -> int: ...
def window_set_transient(window: Gtk.Window) -> None: ...
def window_set_transient_for(window: Gtk.Window, handle: GLib.Bytes) -> None: ...
def window_set_transient_for_display(
    window: Gtk.Window, display: Gimp.Display
) -> None: ...
def zoom_button_new(
    model: ZoomModel, zoom_type: ZoomType, icon_size: Gtk.IconSize
) -> Gtk.Widget: ...
